/* ═══════════════════════════════════════════════════════
   WITCH SHOP GAME - Game Data (英语学习版)

   【玩法改造】
   - 道具名称全部采用四六级英语词汇
   - 每个道具有 word（英文单词）+ meaning（中文释义）
   - 完成订单 = 在键盘区正确拼写该单词
   - keys[] 字段保持兼容（与 word 一致）
═══════════════════════════════════════════════════════ */

/* ─── PHASES / PROGRESSION ─── */
const PHASES = [
  { id: 0, name: '初学者',    coinsNeeded: 0,    label: '✨ 初学者' },
  { id: 1, name: '魔药师',    coinsNeeded: 200,  label: '🧪 魔药师' },
  { id: 2, name: '占卜者',    coinsNeeded: 600,  label: '🔮 占卜者' },
  { id: 3, name: '符文师',    coinsNeeded: 1400, label: '✨ 符文师' },
  { id: 4, name: '大魔女',    coinsNeeded: 3000, label: '⭐ 大魔女'  },
];

/* ─── POTION RECIPES ─── */
// price: 商品价格，影响订单需要拼写的单词数量和单词难度
// unlockCost: 解锁该道具需要的金币数量（可选，不设置则默认已解锁）
const POTIONS = [
  {
    id: 'moon_cookie',
    name: '月糖饼干',
    icon: '🍪',
    price: 40,
    tier: 1,
    desc: '普通但温暖的小点心，适合日常维系关系。',
    intro: '烤盘边缘还沾着月光糖霜，第一批月糖饼干让小店闻起来像深夜茶会。',
    unlocked: true,
    giftable: true,
    giftTags: ['daily', 'comfort', 'gentle'],
    giftBaseExp: 2,
    giftCost: 40,
    legacyGiftId: 'moon_cookie',
  },
  {
    id: 'star_letter',
    name: '星砂信笺',
    icon: '💌',
    price: 120,
    tier: 1,
    desc: '写下感谢与邀约，更快拉近彼此距离。',
    intro: '星砂在纸面上慢慢沉降，像一封还没寄出的温柔邀约。',
    unlocked: true,
    giftable: true,
    giftTags: ['story', 'travel', 'gentle'],
    giftBaseExp: 5,
    giftCost: 120,
    legacyGiftId: 'star_letter',
  },
  {
    id: 'heal',
    name: '治愈药水',
    icon: '🧪',
    price: 20,
    tier: 1,
    desc: '治愈轻伤，回复体力',
    intro: '第一瓶治愈药水让小店闻起来像雨后的草药架。',
    unlocked: true,
    giftable: true,
    giftTags: ['healing', 'gentle', 'daily'],
    giftBaseExp: 2,
    giftCost: 12,
  },
  {
    id: 'calm',
    name: '安眠药水',
    icon: '💜',
    price: 28,
    tier: 1,
    desc: '带来安稳的睡眠',
    intro: '淡紫色药液在瓶底轻轻打转，像把一小段安稳梦境封进玻璃里。',
    unlocked: true,
    giftable: true,
    giftTags: ['comfort', 'dream', 'gentle'],
    giftBaseExp: 2,
    giftCost: 16,
  },
  {
    id: 'lucky',
    name: '幸运药水',
    icon: '🍀',
    price: 35,
    tier: 1,
    desc: '今天手气不错！',
    intro: '幸运药水冒出细小气泡，仿佛连柜台上的铜币都在悄悄翻面。',
    unlocked: true,
    giftable: true,
    giftTags: ['luck', 'travel', 'trade'],
    giftBaseExp: 3,
    giftCost: 22,
  },
  {
    id: 'vanish',
    name: '隐身药水',
    icon: '👁️',
    price: 50,
    tier: 2,
    desc: '暂时让你消失无踪',
    unlocked: false,
    unlockCost: 50,
  },
  {
    id: 'vigor',
    name: '力量药水',
    icon: '💪',
    price: 45,
    tier: 2,
    desc: '力大如牛，一时之勇',
    unlocked: false,
    unlockCost: 60,
  },
  {
    id: 'recall',
    name: '记忆药水',
    icon: '🧠',
    price: 60,
    tier: 2,
    desc: '唤回珍贵的回忆',
    unlocked: false,
    unlockCost: 80,
  },
  {
    id: 'speed',
    name: '迅捷药水',
    icon: '⚡',
    price: 55,
    tier: 2,
    desc: '快如闪电，身轻如燕',
    unlocked: false,
    unlockCost: 100,
  },
  {
    id: 'antidote',
    name: '解毒药水',
    icon: '🍵',
    price: 65,
    tier: 2,
    desc: '祛除体内的毒素',
    unlocked: false,
    unlockCost: 120,
  },
  {
    id: 'ancient',
    name: '龙息酿',
    icon: '🐉',
    price: 120,
    tier: 3,
    desc: '传说中的古老秘方',
    unlocked: false,
    unlockCost: 200,
  },
  {
    id: 'serene',
    name: '月华水',
    icon: '🌙',
    price: 80,
    tier: 3,
    desc: '月夜采集的神圣之水',
    unlocked: false,
    unlockCost: 150,
  },
  {
    id: 'fire_resist',
    name: '抗火药水',
    icon: '🔥',
    price: 70,
    tier: 3,
    desc: '在烈焰中行走而不伤',
    unlocked: false,
    unlockCost: 180,
  },
  {
    id: 'water_breath',
    name: '水下呼吸药水',
    icon: '🌊',
    price: 75,
    tier: 3,
    desc: '在深海中自由呼吸',
    unlocked: false,
    unlockCost: 200,
  },
  {
    id: 'night_vision',
    name: '夜视药水',
    icon: '🦉',
    price: 65,
    tier: 3,
    desc: '黑暗中看清一切',
    unlocked: false,
    unlockCost: 160,
  },
  {
    id: 'regeneration',
    name: '再生药水',
    icon: '💚',
    price: 90,
    tier: 3,
    desc: '持续恢复生命力',
    unlocked: false,
    unlockCost: 250,
  },
  {
    id: 'levitation',
    name: '漂浮药水',
    icon: '☁️',
    price: 85,
    tier: 4,
    desc: '违抗重力的魔法',
    unlocked: false,
    unlockCost: 300,
  },
  {
    id: 'transformation',
    name: '变形药水',
    icon: '🦋',
    price: 100,
    tier: 4,
    desc: '短暂改变形态',
    unlocked: false,
    unlockCost: 350,
  },
  {
    id: 'time_slow',
    name: '时光缓流药水',
    icon: '⏳',
    price: 110,
    tier: 4,
    desc: '让时间为你放慢脚步',
    unlocked: false,
    unlockCost: 400,
  },
  {
    id: 'berserker',
    name: '狂战士药水',
    icon: '⚔️',
    price: 95,
    tier: 4,
    desc: '释放内心的野性力量',
    unlocked: false,
    unlockCost: 380,
  },
  {
    id: 'ethereal',
    name: '虚化药水',
    icon: '👻',
    price: 130,
    tier: 4,
    desc: '穿越物质世界',
    unlocked: false,
    unlockCost: 450,
  },
  {
    id: 'phoenix',
    name: '凤凰之泪',
    icon: '🔆',
    price: 200,
    tier: 4,
    desc: '传说能令人重生的神药',
    unlocked: false,
    unlockCost: 600,
  },
];

/* ─── DIVINATION SERVICES ─── */
const DIVINATIONS = [
  {
    id: 'tarot_simple',
    name: '塔罗牌占卜',
    icon: '🃏',
    price: 40,
    tier: 2,
    desc: '揭示命运的轨迹',
    intro: '第一副塔罗牌在桌面摊开，命运的边角从烛光里露出一点影子。',
    unlocked: false,
    unlockCost: 100,
    giftable: true,
    giftTags: ['fate', 'mystery', 'story'],
    giftBaseExp: 4,
    giftCost: 28,
  },
  {
    id: 'crystal_ball',
    name: '水晶球预言',
    icon: '🔮',
    price: 65,
    tier: 2,
    desc: '窥探未来的迷雾',
    unlocked: false,
    unlockCost: 120,
  },
  {
    id: 'star_read',
    name: '星象解读',
    icon: '⭐',
    price: 55,
    tier: 3,
    desc: '以星辰为向导',
    unlocked: false,
    unlockCost: 150,
  },
  {
    id: 'bone_cast',
    name: '骨符卜算',
    icon: '🦴',
    price: 90,
    tier: 3,
    desc: '古老的骨符占卜术',
    unlocked: false,
    unlockCost: 180,
  },
  {
    id: 'palm_reading',
    name: '掌纹解读',
    icon: '✋',
    price: 45,
    tier: 2,
    desc: '从掌纹中看出过去与未来',
    unlocked: false,
    unlockCost: 110,
  },
  {
    id: 'tea_leaves',
    name: '茶叶占卜',
    icon: '🍵',
    price: 50,
    tier: 2,
    desc: '从茶叶的形状预知未来',
    unlocked: false,
    unlockCost: 130,
  },
  {
    id: 'rune_stones',
    name: '卢恩石占卜',
    icon: '🪨',
    price: 70,
    tier: 3,
    desc: '古老的北欧占卜术',
    unlocked: false,
    unlockCost: 200,
  },
  {
    id: 'pendulum',
    name: '灵摆占卜',
    icon: '⚖️',
    price: 60,
    tier: 3,
    desc: '让灵摆告诉你答案',
    unlocked: false,
    unlockCost: 170,
  },
  {
    id: 'mirror_scrying',
    name: '魔镜占卜',
    icon: '🪞',
    price: 80,
    tier: 3,
    desc: '透过魔镜窥见真相',
    unlocked: false,
    unlockCost: 220,
  },
  {
    id: 'dream_reading',
    name: '解梦',
    icon: '💤',
    price: 55,
    tier: 3,
    desc: '解读梦境中的预兆',
    unlocked: false,
    unlockCost: 160,
  },
  {
    id: 'numerology',
    name: '数字命理',
    icon: '🔢',
    price: 65,
    tier: 3,
    desc: '从数字中揭示命运',
    unlocked: false,
    unlockCost: 190,
  },
  {
    id: 'oracle_cards',
    name: '神谕卡占卜',
    icon: '🎴',
    price: 75,
    tier: 3,
    desc: '神灵的讯息',
    unlocked: false,
    unlockCost: 210,
  },
  {
    id: 'astrology',
    name: '星盘解读',
    icon: '♈',
    price: 100,
    tier: 4,
    desc: '完整的星象图解析',
    unlocked: false,
    unlockCost: 300,
  },
  {
    id: 'crystal_scrying',
    name: '水晶透视',
    icon: '💎',
    price: 110,
    tier: 4,
    desc: '通过水晶看见幻象',
    unlocked: false,
    unlockCost: 350,
  },
  {
    id: 'spirit_board',
    name: '通灵板',
    icon: '👁️‍🗨️',
    price: 95,
    tier: 4,
    desc: '与灵魂对话',
    unlocked: false,
    unlockCost: 320,
  },
  {
    id: 'smoke_reading',
    name: '烟雾占卜',
    icon: '💨',
    price: 85,
    tier: 4,
    desc: '从香烟的形状预知未来',
    unlocked: false,
    unlockCost: 280,
  },
  {
    id: 'sand_divination',
    name: '沙盘占卜',
    icon: '🏜️',
    price: 90,
    tier: 4,
    desc: '沙粒描绘出的命运',
    unlocked: false,
    unlockCost: 300,
  },
  {
    id: 'moon_reading',
    name: '月相占卜',
    icon: '🌙',
    price: 105,
    tier: 4,
    desc: '月亮的盈亏预示着变化',
    unlocked: false,
    unlockCost: 380,
  },
  {
    id: 'blood_prophecy',
    name: '血之预言',
    icon: '🩸',
    price: 130,
    tier: 4,
    desc: '以血为媒介的强大占卜',
    unlocked: false,
    unlockCost: 450,
  },
  {
    id: 'fate_weaving',
    name: '命运编织',
    icon: '🧵',
    price: 150,
    tier: 4,
    desc: '传说能改写命运的禁忌占卜',
    unlocked: false,
    unlockCost: 500,
  },
];

/* ─── CHARM SERVICES ─── */
const CHARMS = [
  {
    id: 'love_charm',
    name: '爱情符咒',
    icon: '💕',
    price: 50,
    tier: 3,
    desc: '让心意得以传达',
    unlocked: false,
    unlockCost: 150,
  },
  {
    id: 'ward_charm',
    name: '辟邪符咒',
    icon: '🛡️',
    price: 45,
    tier: 3,
    desc: '抵御邪恶与不幸',
    intro: '辟邪符咒在门铃旁亮了一瞬，小店的夜风似乎也变得温和。',
    unlocked: false,
    unlockCost: 140,
    giftable: true,
    giftTags: ['protection', 'holy', 'safety'],
    giftBaseExp: 4,
    giftCost: 30,
  },
  {
    id: 'wealth_charm',
    name: '招财符咒',
    icon: '💰',
    price: 70,
    tier: 3,
    desc: '财运滚滚而来',
    unlocked: false,
    unlockCost: 180,
  },
  {
    id: 'wisdom_charm',
    name: '智慧符文',
    icon: '📖',
    price: 80,
    tier: 4,
    desc: '开启心灵的智慧之门',
    unlocked: false,
    unlockCost: 250,
  },
  {
    id: 'health_charm',
    name: '健康符咒',
    icon: '💚',
    price: 55,
    tier: 3,
    desc: '保佑身体康健',
    unlocked: false,
    unlockCost: 160,
  },
  {
    id: 'courage_charm',
    name: '勇气符文',
    icon: '🦁',
    price: 60,
    tier: 3,
    desc: '赋予无畏的勇气',
    unlocked: false,
    unlockCost: 170,
  },
  {
    id: 'peace_charm',
    name: '和平符咒',
    icon: '🕊️',
    price: 65,
    tier: 3,
    desc: '化解争端与冲突',
    unlocked: false,
    unlockCost: 190,
  },
  {
    id: 'binding_charm',
    name: '契约符文',
    icon: '🔗',
    price: 75,
    tier: 3,
    desc: '确保约定必被遵守',
    unlocked: false,
    unlockCost: 200,
  },
  {
    id: 'travel_charm',
    name: '旅行护符',
    icon: '🧭',
    price: 50,
    tier: 3,
    desc: '保护旅途平安',
    unlocked: false,
    unlockCost: 150,
  },
  {
    id: 'memory_charm',
    name: '记忆符文',
    icon: '🧠',
    price: 70,
    tier: 3,
    desc: '增强记忆与学习能力；作为礼物时也承载共同经历。',
    intro: '记忆符文的纹路像旧书页上的折痕，适合送给仍记得约定的人。',
    unlocked: false,
    unlockCost: 210,
    giftable: true,
    giftTags: ['story', 'memory', 'comfort'],
    giftBaseExp: 10,
    giftCost: 300,
    legacyGiftId: 'memory_charm',
  },
  {
    id: 'beauty_charm',
    name: '魅力符咒',
    icon: '✨',
    price: 85,
    tier: 4,
    desc: '提升个人魅力',
    unlocked: false,
    unlockCost: 280,
  },
  {
    id: 'silence_charm',
    name: '静音符文',
    icon: '🤫',
    price: 65,
    tier: 4,
    desc: '消除一切声音',
    unlocked: false,
    unlockCost: 240,
  },
  {
    id: 'truth_charm',
    name: '真实符咒',
    icon: '👁️',
    price: 90,
    tier: 4,
    desc: '无法说谎的约束',
    unlocked: false,
    unlockCost: 320,
  },
  {
    id: 'growth_charm',
    name: '生长符文',
    icon: '🌱',
    price: 75,
    tier: 4,
    desc: '加速植物生长',
    unlocked: false,
    unlockCost: 260,
  },
  {
    id: 'sleep_charm',
    name: '沉睡符咒',
    icon: '😴',
    price: 80,
    tier: 4,
    desc: '引导进入深度睡眠',
    unlocked: false,
    unlockCost: 290,
  },
  {
    id: 'light_charm',
    name: '光明符文',
    icon: '💡',
    price: 70,
    tier: 4,
    desc: '驱散黑暗与恐惧',
    unlocked: false,
    unlockCost: 270,
  },
  {
    id: 'shadow_charm',
    name: '暗影符咒',
    icon: '🌑',
    price: 95,
    tier: 4,
    desc: '融入阴影之中',
    unlocked: false,
    unlockCost: 350,
  },
  {
    id: 'element_charm',
    name: '元素符文',
    icon: '🔥',
    price: 110,
    tier: 4,
    desc: '操控基础元素',
    unlocked: false,
    unlockCost: 400,
  },
  {
    id: 'soul_charm',
    name: '灵魂符咒',
    icon: '👻',
    price: 120,
    tier: 4,
    desc: '与灵魂沟通的桥梁',
    unlocked: false,
    unlockCost: 450,
  },
  {
    id: 'eternal_charm',
    name: '永恒符文',
    icon: '♾️',
    price: 150,
    tier: 4,
    desc: '传说能让符咒永不消失',
    unlocked: false,
    unlockCost: 550,
  },
];

/* ─── ALCHEMY SERVICES ─── */
const ALCHEMY = [
  {
    id: 'fate_crystal',
    name: '命运水晶',
    icon: '💎',
    price: 800,
    tier: 4,
    desc: '昂贵而稀有的水晶，适合后期消耗金币并冲刺最终羁绊。',
    intro: '命运水晶折射出许多尚未发生的重逢，昂贵得像一条被买下的可能性。',
    unlocked: false,
    unlockCost: 800,
    giftable: true,
    giftTags: ['fate', 'mystery', 'precious'],
    giftBaseExp: 22,
    giftCost: 800,
    legacyGiftId: 'fate_crystal',
  },
  {
    id: 'transmute_copper',
    name: '炼铜成银',
    icon: '⚗️',
    price: 100,
    tier: 4,
    desc: '将普通金属提炼升华',
    intro: '炼金炉里响起清脆回声，第一块银光金属让商人们多看了柜台一眼。',
    unlocked: false,
    unlockCost: 300,
    giftable: true,
    giftTags: ['craft', 'metal', 'trade'],
    giftBaseExp: 5,
    giftCost: 60,
  },
  {
    id: 'elixir_youth',
    name: '青春灵药',
    icon: '✨',
    price: 150,
    tier: 4,
    desc: '据说能留住青春',
    unlocked: false,
    unlockCost: 400,
  },
  {
    id: 'philosophers',
    name: '贤者之石碎片',
    icon: '💎',
    price: 300,
    tier: 4,
    desc: '炼金术的终极追求',
    unlocked: false,
    unlockCost: 800,
  },
  {
    id: 'metal_purify',
    name: '金属提纯',
    icon: '⚙️',
    price: 90,
    tier: 4,
    desc: '提炼出最纯净的金属',
    unlocked: false,
    unlockCost: 280,
  },
  {
    id: 'essence_extract',
    name: '精华萃取',
    icon: '🧬',
    price: 110,
    tier: 4,
    desc: '提取物质的核心精华',
    unlocked: false,
    unlockCost: 320,
  },
  {
    id: 'crystal_grow',
    name: '水晶培育',
    icon: '💎',
    price: 120,
    tier: 4,
    desc: '催生魔法水晶',
    unlocked: false,
    unlockCost: 350,
  },
  {
    id: 'gem_synthesis',
    name: '宝石合成',
    icon: '💍',
    price: 130,
    tier: 4,
    desc: '创造完美的宝石',
    unlocked: false,
    unlockCost: 380,
  },
  {
    id: 'life_essence',
    name: '生命精华',
    icon: '🌺',
    price: 140,
    tier: 4,
    desc: '提炼生命的能量',
    unlocked: false,
    unlockCost: 420,
  },
  {
    id: 'soul_distill',
    name: '灵魂蒸馏',
    icon: '👻',
    price: 160,
    tier: 4,
    desc: '提炼灵魂的本质',
    unlocked: false,
    unlockCost: 450,
  },
  {
    id: 'time_extract',
    name: '时光萃取',
    icon: '⏰',
    price: 170,
    tier: 4,
    desc: '捕捉流逝的时间',
    unlocked: false,
    unlockCost: 480,
  },
  {
    id: 'element_fusion',
    name: '元素融合',
    icon: '🌟',
    price: 150,
    tier: 4,
    desc: '将不同元素完美结合',
    unlocked: false,
    unlockCost: 440,
  },
  {
    id: 'void_craft',
    name: '虚空锻造',
    icon: '🌌',
    price: 180,
    tier: 4,
    desc: '在虚空中创造物质',
    unlocked: false,
    unlockCost: 500,
  },
  {
    id: 'light_condense',
    name: '光之凝聚',
    icon: '☀️',
    price: 140,
    tier: 4,
    desc: '将光芒凝聚成实体',
    unlocked: false,
    unlockCost: 420,
  },
  {
    id: 'shadow_forge',
    name: '暗影锻造',
    icon: '🌑',
    price: 145,
    tier: 4,
    desc: '以黑暗塑造形体',
    unlocked: false,
    unlockCost: 430,
  },
  {
    id: 'star_extract',
    name: '星辰精粹',
    icon: '⭐',
    price: 190,
    tier: 4,
    desc: '提炼星辰的力量',
    unlocked: false,
    unlockCost: 550,
  },
  {
    id: 'moon_essence',
    name: '月华精华',
    icon: '🌙',
    price: 175,
    tier: 4,
    desc: '收集月光的能量',
    unlocked: false,
    unlockCost: 490,
  },
  {
    id: 'dragon_blood',
    name: '龙血炼化',
    icon: '🐉',
    price: 220,
    tier: 4,
    desc: '炼化龙族的血液',
    unlocked: false,
    unlockCost: 600,
  },
  {
    id: 'divine_craft',
    name: '神圣锻造',
    icon: '✝️',
    price: 250,
    tier: 4,
    desc: '以神圣之力锻造',
    unlocked: false,
    unlockCost: 700,
  },
  {
    id: 'chaos_synthesis',
    name: '混沌合成',
    icon: '🌪️',
    price: 280,
    tier: 4,
    desc: '从混沌中创造秩序',
    unlocked: false,
    unlockCost: 750,
  },
  {
    id: 'immortal_elixir',
    name: '不朽灵药',
    icon: '♾️',
    price: 350,
    tier: 4,
    desc: '传说中的永生之药',
    unlocked: false,
    unlockCost: 1000,
  },
];

/* ─── PERSONALITY TRAITS POOL ─── */
// 性格标签池：所有NPC共享这些性格特质
const PERSONALITY_TRAITS = {
  friendly: {
    label: '友好的',
    dialogueStyle: 'warm', // 温暖、热情的语气
    tipModifier: 0,
  },
  honorable: {
    label: '荣誉的',
    dialogueStyle: 'formal', // 正式、庄重的语气
    tipModifier: 0.1,
  },
  shrewd: {
    label: '精明的',
    dialogueStyle: 'calculating', // 精打细算的语气
    tipModifier: 0.2,
  },
  timid: {
    label: '胆怯的',
    dialogueStyle: 'nervous', // 紧张、不安的语气
    tipModifier: -0.2,
  },
  arrogant: {
    label: '傲慢的',
    dialogueStyle: 'haughty', // 傲慢、自大的语气
    tipModifier: 0.3,
  },
  humble: {
    label: '谦逊的',
    dialogueStyle: 'polite', // 礼貌、谦卑的语气
    tipModifier: -0.1,
  },
  romantic: {
    label: '浪漫的',
    dialogueStyle: 'dreamy', // 梦幻、感性的语气
    tipModifier: 0.1,
  },
  curious: {
    label: '好奇的',
    dialogueStyle: 'inquisitive', // 好奇、询问的语气
    tipModifier: 0.2,
  },
  melancholic: {
    label: '忧郁的',
    dialogueStyle: 'sad', // 悲伤、忧郁的语气
    tipModifier: 0.5,
  },
  wise: {
    label: '睿智的',
    dialogueStyle: 'philosophical', // 哲理、深邃的语气
    tipModifier: 0.4,
  },
  gruff: {
    label: '粗鲁直率的',
    dialogueStyle: 'blunt', // 直率、粗鲁的语气
    tipModifier: 0.2,
  },
  elegant: {
    label: '优雅的',
    dialogueStyle: 'refined', // 优雅、精致的语气
    tipModifier: 0.6,
  },
  devout: {
    label: '虔诚的',
    dialogueStyle: 'reverent', // 虔诚、敬畏的语气
    tipModifier: 0.3,
  },
  cautious: {
    label: '谨慎的',
    dialogueStyle: 'wary', // 警惕、小心的语气
    tipModifier: 0.1,
  },
  cheerful: {
    label: '欢快的',
    dialogueStyle: 'jovial', // 欢快、活泼的语气
    tipModifier: 0,
  },
  eccentric: {
    label: '古怪的',
    dialogueStyle: 'quirky', // 古怪、奇特的语气
    tipModifier: 0.3,
  },
  playful: {
    label: '顽皮的',
    dialogueStyle: 'mischievous', // 调皮、恶作剧的语气
    tipModifier: 1.0,
  },
  mysterious: {
    label: '神秘的',
    dialogueStyle: 'cryptic', // 神秘、隐晦的语气
    tipModifier: 0.5,
  },
  innocent: {
    label: '天真的',
    dialogueStyle: 'naive', // 天真、单纯的语气
    tipModifier: 0.2,
  },
  cunning: {
    label: '狡猾的',
    dialogueStyle: 'sly', // 狡猾、阴险的语气
    tipModifier: 0.7,
  },
};

/* ─── CUSTOMER IDENTITIES (职业身份) ─── */
// 身份池：定义不同的职业/种族身份
const CUSTOMER_IDENTITIES = {
  traveler: {
    name: '旅行者',
    emoji: '🧳',
    preferModule: 'potions',
    baseTipMultiplier: 1.0,
  },
  knight: {
    name: '骑士',
    emoji: '⚔️',
    preferModule: 'potions',
    baseTipMultiplier: 1.1,
  },
  merchant: {
    name: '商人',
    emoji: '💼',
    preferModule: 'potions',
    baseTipMultiplier: 1.3,
  },
  student: {
    name: '学生',
    emoji: '📚',
    preferModule: 'potions',
    baseTipMultiplier: 0.8,
  },
  noble: {
    name: '贵族',
    emoji: '👑',
    preferModule: 'divination',
    baseTipMultiplier: 1.5,
  },
  farmer: {
    name: '农夫',
    emoji: '🌾',
    preferModule: 'divination',
    baseTipMultiplier: 0.9,
  },
  lover: {
    name: '恋人',
    emoji: '💑',
    preferModule: 'charms',
    baseTipMultiplier: 1.2,
  },
  scholar: {
    name: '学者',
    emoji: '🔬',
    preferModule: 'alchemy',
    baseTipMultiplier: 1.4,
  },
  ghost: {
    name: '幽灵',
    emoji: '👻',
    preferModule: 'divination',
    baseTipMultiplier: 2.0,
  },
  elf: {
    name: '精灵',
    emoji: '🧝',
    preferModule: 'charms',
    baseTipMultiplier: 1.6,
  },
  dwarf: {
    name: '矮人',
    emoji: '⛏️',
    preferModule: 'potions',
    baseTipMultiplier: 1.3,
  },
  vampire: {
    name: '吸血鬼',
    emoji: '🧛',
    preferModule: 'alchemy',
    baseTipMultiplier: 1.8,
  },
  priest: {
    name: '牧师',
    emoji: '⛪',
    preferModule: 'charms',
    baseTipMultiplier: 1.4,
  },
  witch_hunter: {
    name: '猎魔人',
    emoji: '🗡️',
    preferModule: 'potions',
    baseTipMultiplier: 1.2,
  },
  bard: {
    name: '吟游诗人',
    emoji: '🎵',
    preferModule: 'divination',
    baseTipMultiplier: 1.1,
  },
  alchemist: {
    name: '炼金术士',
    emoji: '🔬',
    preferModule: 'alchemy',
    baseTipMultiplier: 1.5,
  },
  dragon: {
    name: '幼龙',
    emoji: '🐲',
    preferModule: 'alchemy',
    baseTipMultiplier: 2.5,
  },
  necromancer: {
    name: '死灵法师',
    emoji: '💀',
    preferModule: 'divination',
    baseTipMultiplier: 1.7,
  },
  fairy: {
    name: '花仙子',
    emoji: '🧚',
    preferModule: 'charms',
    baseTipMultiplier: 1.3,
  },
  demon: {
    name: '恶魔',
    emoji: '😈',
    preferModule: 'alchemy',
    baseTipMultiplier: 2.0,
  },
};

/* ─── CUSTOMER TYPES (组合的NPC配置) ─── */
// 预设的身份+性格组合，用于生成具体的NPC角色
const CUSTOMER_TYPES = [

  {
    id: 'traveler',
    name: '旅行者',
    charName: '塞勒斯',
    emoji: '🧳',
    personality: 'friendly', // 友好的
    dialogue: [
      '我在旅途中受了点伤……',
      '听说你的药水效果很好！',
      '请给我最好的！',
    ],
    preferModule: 'potions',
    tipMultiplier: 1.0,
    phase: 0,
  },
  {
    id: 'knight',
    name: '骑士',
    charName: '艾德里安',
    emoji: '⚔️',
    personality: 'honorable', // 荣誉的
    dialogue: [
      '魔女，我需要你的帮助。',
      '战场上我需要力量药水。',
      '这是我最后的金币了……',
    ],
    preferModule: 'potions',
    tipMultiplier: 1.1,
    phase: 0,
  },
  {
    id: 'merchant',
    name: '商人',
    charName: '马库斯',
    emoji: '💼',
    personality: 'shrewd', // 精明的
    dialogue: [
      '做生意要靠运气啊！',
      '给我来一瓶幸运药水吧。',
      '价格好说，质量第一！',
    ],
    preferModule: 'potions',
    tipMultiplier: 1.3,
    phase: 0,
  },
  {
    id: 'student',
    name: '学生',
    charName: '林恩',
    emoji: '📚',
    personality: 'timid', // 胆怯的
    dialogue: [
      '考试快到了，好紧张……',
      '有没有什么能帮助记忆的？',
      '我钱不多，能便宜点吗？',
    ],
    preferModule: 'potions',
    tipMultiplier: 0.8,
    phase: 0,
  },
  {
    id: 'noble',
    name: '贵族',
    charName: '艾里克',
    emoji: '👑',
    personality: 'arrogant', // 傲慢的
    dialogue: [
      '本公爵需要一些特别的服务。',
      '价格不是问题，质量才是关键。',
      '快点，我时间宝贵！',
    ],
    preferModule: 'divination',
    tipMultiplier: 1.5,
    phase: 1,
  },
  {
    id: 'farmer',
    name: '农夫',
    charName: '托马斯',
    emoji: '🌾',
    personality: 'humble', // 谦逊的
    dialogue: [
      '今年收成不好，想占卜一下……',
      '明年会更好吧？',
      '谢谢你，魔女大人！',
    ],
    preferModule: 'divination',
    tipMultiplier: 0.9,
    phase: 1,
  },
  {
    id: 'lover',
    name: '恋人',
    charName: '朱利安',
    emoji: '💑',
    personality: 'romantic', // 浪漫的
    dialogue: [
      '我……我喜欢上了一个人……',
      '有什么能帮助我表白的符咒吗？',
      '真的有效果吗？',
    ],
    preferModule: 'charms',
    tipMultiplier: 1.2,
    phase: 2,
  },
  {
    id: 'scholar',
    name: '学者',
    charName: '维克多',
    emoji: '🔬',
    personality: 'curious', // 好奇的
    dialogue: [
      '我在研究古代炼金术……',
      '需要一些特殊的材料。',
      '这对科学很重要！',
    ],
    preferModule: 'alchemy',
    tipMultiplier: 1.4,
    phase: 3,
  },
  {
    id: 'ghost',
    name: '幽灵',
    charName: '埃利亚斯',
    emoji: '👻',
    personality: 'melancholic', // 忧郁的
    dialogue: [
      '嘘……我只是路过……',
      '能帮我占卜一下来世吗？',
      '谢谢……再会……',
    ],
    preferModule: 'divination',
    tipMultiplier: 2.0,
    phase: 2,
  },
  {
    id: 'elf',
    name: '精灵',
    charName: '希尔凡',
    emoji: '🧝',
    personality: 'wise', // 睿智的
    dialogue: [
      '森林里的能量失衡了……',
      '我需要一些符文来恢复平衡。',
      '自然会回报你的善意！',
    ],
    preferModule: 'charms',
    tipMultiplier: 1.6,
    phase: 2,
  },
  {
    id: 'dwarf',
    name: '矮人',
    charName: '格罗因',
    emoji: '⛏️',
    personality: 'gruff', // 粗鲁直率的
    dialogue: [
      '矿洞深处有些不对劲……',
      '给我来瓶能看清黑暗的药水！',
      '我们矮人向来直来直去！',
    ],
    preferModule: 'potions',
    tipMultiplier: 1.3,
    phase: 1,
  },
  {
    id: 'vampire',
    name: '吸血鬼',
    charName: '达里安',
    emoji: '🧛',
    personality: 'elegant', // 优雅的
    dialogue: [
      '夜晚才是我的时间……',
      '我需要一些特殊的服务。',
      '别担心，我已经用过晚餐了。',
    ],
    preferModule: 'alchemy',
    tipMultiplier: 1.8,
    phase: 3,
  },
  {
    id: 'priest',
    name: '牧师',
    charName: '塞巴斯',
    emoji: '⛪',
    personality: 'devout', // 虔诚的
    dialogue: [
      '神殿需要一些祝福……',
      '您的魔法是否符合教义呢？',
      '愿光明庇佑你。',
    ],
    preferModule: 'charms',
    tipMultiplier: 1.4,
    phase: 2,
  },
  {
    id: 'witch_hunter',
    name: '猎魔人',
    charName: '加雷特',
    emoji: '🗡️',
    personality: 'cautious', // 谨慎的
    dialogue: [
      '我在追踪一只怪物……',
      '需要一些药水补给。',
      '你的魔法……是善意的对吧？',
    ],
    preferModule: 'potions',
    tipMultiplier: 1.2,
    phase: 1,
  },
  {
    id: 'bard',
    name: '吟游诗人',
    charName: '菲恩',
    emoji: '🎵',
    personality: 'cheerful', // 欢快的
    dialogue: [
      '我要为一首新歌寻找灵感！',
      '能否预见我的未来？',
      '这将成为传世的歌谣！',
    ],
    preferModule: 'divination',
    tipMultiplier: 1.1,
    phase: 1,
  },
  {
    id: 'alchemist',
    name: '炼金术士',
    charName: '奥利弗',
    emoji: '🔬',
    personality: 'eccentric', // 古怪的
    dialogue: [
      '同行啊！我遇到了瓶颈……',
      '能交流一下炼金的心得吗？',
      '真是精妙的技艺！',
    ],
    preferModule: 'alchemy',
    tipMultiplier: 1.5,
    phase: 3,
  },
  {
    id: 'dragon',
    name: '幼龙',
    charName: '伊格尼斯',
    emoji: '🐲',
    personality: 'playful', // 顽皮的
    dialogue: [
      '咕噜噜……人类的魔法真有趣……',
      '给我看看你最强的炼金术！',
      '不错，值得收藏。',
    ],
    preferModule: 'alchemy',
    tipMultiplier: 2.5,
    phase: 4,
  },
  {
    id: 'necromancer',
    name: '死灵法师',
    charName: '莫里斯',
    emoji: '💀',
    personality: 'mysterious', // 神秘的
    dialogue: [
      '生与死的界限……如此模糊……',
      '我需要与灵魂对话的工具。',
      '死亡只是另一种存在。',
    ],
    preferModule: 'divination',
    tipMultiplier: 1.7,
    phase: 3,
  },
  {
    id: 'fairy',
    name: '花仙子',
    charName: '蒂娜',
    emoji: '🧚',
    personality: 'innocent', // 天真的
    dialogue: [
      '花园需要魔法的滋养！',
      '有让植物生长的符文吗？',
      '真是善良的魔女呢~',
    ],
    preferModule: 'charms',
    tipMultiplier: 1.3,
    phase: 2,
  },
  {
    id: 'demon',
    name: '恶魔',
    charName: '阿扎泽尔',
    emoji: '😈',
    personality: 'cunning', // 狡猾的
    dialogue: [
      '嘿嘿……有趣的小店……',
      '来做个交易如何？',
      '我会记住你的，魔女。',
    ],
    preferModule: 'alchemy',
    tipMultiplier: 2.0,
    phase: 4,
  },
];

/* ─── SHOP UNLOCK ITEMS ─── */
const SHOP_UNLOCKS = [
  {
    id: 'unlock_divination',
    name: '占卜工作台',
    icon: '🔮',
    desc: '解锁占卜服务，吸引更多神秘客人',
    cost: 150,
    module: 'divination',
    purchased: false,
    phase: 0,
  },
  {
    id: 'unlock_charms',
    name: '符文刻印台',
    icon: '✨',
    desc: '解锁符咒服务，施展古老魔法',
    cost: 400,
    module: 'charms',
    purchased: false,
    phase: 1,
  },
  {
    id: 'unlock_alchemy',
    name: '炼金熔炉',
    icon: '⚗️',
    desc: '解锁炼金术，点石成金！',
    cost: 1000,
    module: 'alchemy',
    purchased: false,
    phase: 2,
  },
];

/* ─── SHOP UPGRADE ITEMS ─── */
const SHOP_UPGRADES = [
  {
    id: 'hint_show',
    name: '释义提示',
    icon: '💡',
    desc: '订单卡片上始终显示单词中文释义',
    cost: 60,
    purchased: false,
    effect: 'hint_show',
    phase: 0,
  },
  {
    id: 'customer_patience',
    name: '客人更有耐心',
    icon: '⏳',
    desc: '订单计时器延长50%',
    cost: 120,
    purchased: false,
    effect: 'patience',
    phase: 0,
  },
  {
    id: 'better_tips',
    name: '慷慨小费',
    icon: '💸',
    desc: '所有订单奖励+20%',
    cost: 200,
    purchased: false,
    effect: 'tips',
    phase: 1,
  },
  {
    id: 'more_orders',
    name: '客源广泛',
    icon: '🚪',
    desc: '同时可有3个待处理订单',
    cost: 300,
    purchased: false,
    effect: 'more_orders',
    phase: 1,
  },
  {
    id: 'vip_customers',
    name: 'VIP接待',
    icon: '⭐',
    desc: '偶尔出现高价值神秘客人',
    cost: 500,
    purchased: false,
    effect: 'vip',
    phase: 2,
  },
  {
    id: 'auto_unlock_recipes',
    name: '古籍解读',
    icon: '📜',
    desc: '自动解锁当前阶段全部配方',
    cost: 800,
    purchased: false,
    effect: 'auto_recipes',
    phase: 3,
  },
];

/* ─── SHOP INVESTMENTS ───
   金币的中长期消耗点：改善店铺气质，并作为店铺故事与隐藏路线的条件。 */
const SHOP_INVESTMENTS = [
  {
    id: 'cozy_corner',
    name: '温暖会客角',
    icon: '🛋️',
    desc: '添置软垫、热茶与小圆桌，让熟客更愿意留下来聊天。',
    cost: 180,
    phase: 0,
    traits: { comfort: 2, fame: 1 },
  },
  {
    id: 'reference_shelf',
    name: '魔法参考书架',
    icon: '📚',
    desc: '补齐药草学、占卜与符文学手册，提升小店的专业感。',
    cost: 320,
    phase: 1,
    traits: { wisdom: 2, fame: 1 },
  },
  {
    id: 'moonlit_signboard',
    name: '月光招牌',
    icon: '🌙',
    desc: '夜晚也会发出柔和银光的招牌，吸引远处的神秘客人。',
    cost: 520,
    phase: 2,
    traits: { mystery: 2, fame: 2 },
  },
  {
    id: 'private_workroom',
    name: '隐秘工坊',
    icon: '🗝️',
    desc: '整理一间只接待可信之人的后室，为更深层故事留下入口。',
    cost: 900,
    phase: 3,
    traits: { mystery: 3, wisdom: 1, comfort: 1 },
  },
];

/* ─── BOND / RELATIONSHIP ITEMS ───
   金币的长期消耗点：购买礼物提升角色羁绊，羁绊会参与后续故事解锁。 */
const BOND_LEVELS = [
  { level: 0, exp: 0, label: '初识' },
  { level: 1, exp: 3, label: '熟客' },
  { level: 2, exp: 8, label: '信赖' },
  { level: 3, exp: 15, label: '亲近' },
  { level: 4, exp: 24, label: '命定' },
];

const DEFAULT_BOND_STAGE_REWARDS = {
  1: '这位熟客开始记住你的店了。',
  2: '你们之间形成了稳定的交易默契。',
  3: '这位熟客愿意向你透露更多个人偏好。',
  4: '你已经成为这位熟客信任的魔女店主。',
};

const BOND_STAGE_REWARDS = {
  traveler: {
    1: '塞勒斯会在远行前优先想到你的柜台。',
    2: '他开始把沿途见闻带回店里，作为下一次故事的线索。',
  },
  knight: {
    1: '艾德里安认可了你稳定可靠的补给。',
    2: '她愿意把巡逻途中的小麻烦交给你处理。',
  },
  vampire: {
    1: '达里安开始认可你的夜间服务。',
    2: '她偶尔会提醒你夜晚客人的偏好。',
  },
  fairy: {
    1: '蒂娜把你的小店列进了花粉路线。',
    2: '她会悄悄告诉你哪些礼物带着好闻的气味。',
  },
};

const BOND_GIFT_LABELS = {
  moon_cookie: '月糖饼干',
  star_letter: '星砂信笺',
  memory_charm: '记忆符文',
  fate_crystal: '命运水晶',
};

// v3.2+: 羁绊礼物由商品/配方系统承载；保留空数组仅用于旧代码兼容。
const BOND_GIFTS = [];

const SPECIAL_NPC_VISIT_LINES = {
  traveler: {
    bond0: ['这家店看起来能让旅人歇口气。', '我在路上听说过你的招牌。'],
    bond1: ['又路过这里了，还是想先进来看看你。', '塞勒斯把旅尘拍掉，笑着说今天只信你的药。'],
    bond2: ['远行前不来你这里补给，总觉得少了什么。', '这次带回来的见闻，想第一个讲给你听。'],
    bond3: ['无论走多远，我都会记得回到这盏灯下。', '塞勒斯把地图收起，说终点暂时写成你的店。'],
  },
  knight: {
    bond0: ['魔女，我需要可靠的补给。', '战场不等人，请让我看看你的本事。'],
    bond1: ['艾德里安向你点头：上次的药水救了我一命。', '我愿意把背后暂时交给你的魔法。'],
    bond2: ['今日不是军令，是我自己想来见你。', '你的柜台旁，竟比营火边更让我安心。'],
    bond3: ['若要守护什么，我希望这间小店也在誓言之中。', '艾德里安摘下手甲，郑重把信任放在你面前。'],
  },
  merchant: {
    bond0: ['听说这里的买卖很有潜力。', '让我看看这笔交易值不值得。'],
    bond1: ['马库斯笑着敲柜台：熟人价？开玩笑的。', '你的货上次卖相不错，今天我带了更好的金币。'],
    bond2: ['账本说该谨慎，但直觉说该相信你。', '若是你推荐的商品，我愿意少砍一次价。'],
    bond3: ['有些交易不写进账本，只记在人情里。', '马库斯合上钱袋，说今天想先听你怎么说。'],
  },
  student: {
    bond0: ['那、那个……这里能帮忙吗？', '我只是想找一点考试用的勇气。'],
    bond1: ['林恩小声说：上次真的有用，谢谢你。', '我又来了，这次没有那么害怕了。'],
    bond2: ['如果是你教我的魔法，我应该能记住。', '林恩把笔记摊开，眼神比从前亮了一点。'],
    bond3: ['我想变得厉害一点，至少能帮上你的忙。', '林恩认真地说，来这里已经像回到安全的教室。'],
  },
  noble: {
    bond0: ['本公爵需要配得上身份的服务。', '希望你的魔法不像传闻那样夸张。'],
    bond1: ['艾里克抬起下巴：勉强承认你值得期待。', '今天准许你按自己的判断推荐。'],
    bond2: ['宫廷里太吵，你这里反而清净。', '若有人质疑你，本公爵会让他们闭嘴。'],
    bond3: ['头衔可以命令人，却不能命令我信任谁。', '艾里克放低声音：所以我亲自来了。'],
  },
  farmer: {
    bond0: ['今年田里的风向有点怪，想请你看看。', '托马斯攥着帽檐，拘谨地站在门口。'],
    bond1: ['上次的建议真管用，麦苗精神多了。', '给你带了点新鲜果子，不值钱，别嫌弃。'],
    bond2: ['村里人现在都说，森林魔女是好心人。', '有难处时，我第一个想到的就是你这里。'],
    bond3: ['丰收时我想把第一篮麦穗送来。', '托马斯笑得朴实：这间店也是我们的好运气。'],
  },
  lover: {
    bond0: ['我有一点……关于心意的烦恼。', '这里真的有能让人勇敢的符咒吗？'],
    bond1: ['朱利安红着脸：上次之后，我好像更敢说话了。', '如果是你听我练习表白，我会安心些。'],
    bond2: ['我开始明白，真心不能全靠魔法。', '但你的魔法，总能让我更接近真实的自己。'],
    bond3: ['今天不是为了别人来的，是想问候你。', '朱利安把花藏在身后，笑得很不擅长掩饰。'],
  },
  scholar: {
    bond0: ['我想验证一种古代炼金假说。', '这间店也许有稀有样本。'],
    bond1: ['维克多推推眼镜：你的结果值得记录。', '上次实验很成功，我想继续与你合作。'],
    bond2: ['论文可以稍后写，先听听你的直觉吧。', '你的经验让书本上的结论变得鲜活。'],
    bond3: ['若知识有温度，大概就是这张柜台的距离。', '维克多认真记录：信任，是今日最重要发现。'],
  },
  ghost: {
    bond0: ['嘘……我只是被灯光吸引。', '这里的风，比墓园暖一点。'],
    bond1: ['埃利亚斯的轮廓清晰了些：你还记得我。', '活人的店里，竟也有适合幽灵的位置。'],
    bond2: ['来世的问题不急，今天想听你说说现世。', '你点亮蜡烛时，他安静地停在光边。'],
    bond3: ['若执念也能变温柔，我愿意常来。', '埃利亚斯低声道别，却没有立刻消失。'],
  },
  elf: {
    bond0: ['森林让我来看看这里的魔力流向。', '愿你的手没有扰乱自然。'],
    bond1: ['希尔凡微笑：树叶说你值得信任。', '今日我带来林间露水，与你交换建议。'],
    bond2: ['你的小店已经成为森林气息的一部分。', '在你身边，古老的风也愿意放轻脚步。'],
    bond3: ['若森林认可一个名字，它会把归路告诉风。', '希尔凡说，风已经记住你了。'],
  },
  dwarf: {
    bond0: ['矿洞里需要实在管用的东西。', '格罗因敲敲柜台：别给我花架子。'],
    bond1: ['上次那瓶够劲！我喜欢实诚手艺。', '你这地方小是小，东西不含糊。'],
    bond2: ['我给你的招牌加固了，别客气。', '矮人的朋友，当然要用最结实的东西。'],
    bond3: ['谁敢砸你的店，先问问我的锤子。', '格罗因别过脸：朋友嘛，就该这样。'],
  },
  vampire: {
    bond0: ['夜色适合拜访有品味的小店。', '达里安微笑得过分优雅。'],
    bond1: ['你的招待比许多古堡晚宴更让人愉快。', '放心，今晚我只对魔法感兴趣。'],
    bond2: ['漫长夜晚里，少有地方值得反复造访。', '你这里的灯光不会刺眼，反而让人想停留。'],
    bond3: ['永生很长，值得珍惜的相遇很少。', '达里安轻声说，今晚想把时间留给你。'],
  },
  priest: {
    bond0: ['愿光明审视这份魔法。', '神殿需要谨慎而温和的帮助。'],
    bond1: ['塞巴斯点头：善意本身也是一种祝福。', '你的魔法若用于守护，神明会看见。'],
    bond2: ['教义之外，我也开始理解人的心愿。', '在这里祈祷时，光似乎更柔软。'],
    bond3: ['愿我以朋友之名，而非审视者之名来访。', '塞巴斯把祝福留在门口，也留给你。'],
  },
  witch_hunter: {
    bond0: ['我需要补给，也需要确认你的立场。', '加雷特的目光仍停在武器附近。'],
    bond1: ['你上次没有趁机害人，我记住了。', '这不是审问，只是一次委托。'],
    bond2: ['有些怪物披着人皮，有些魔女救人性命。', '我正在学习不要用旧规矩判断你。'],
    bond3: ['若有人把你列为猎物，我会先站出来反对。', '加雷特收起银刃，认真看向你。'],
  },
  bard: {
    bond0: ['我来找一段能唱进歌里的奇遇！', '菲恩拨错一个和弦，仍然笑得灿烂。'],
    bond1: ['上次的故事有副歌了，你要听吗？', '你的店非常押韵，真的，相信诗人。'],
    bond2: ['我写了新曲，第一位听众当然是你。', '这里的每次铃响，都像歌曲开头。'],
    bond3: ['若传说需要主角，我想把你的名字唱到最后。', '菲恩弯腰行礼，把最亮的音符献给你。'],
  },
  alchemist: {
    bond0: ['同行！让我看看你的反应式。', '奥利弗抱着冒烟烧瓶冲了进来。'],
    bond1: ['上次爆炸规模适中，成果惊人！', '你的配方让我灵感沸腾。'],
    bond2: ['今天我先不抢实验台，只想交换心得。', '与你合作时，失败也像发现。'],
    bond3: ['若人生是炼成阵，你大概是核心材料。', '奥利弗认真得不像在开玩笑。'],
  },
  dragon: {
    bond0: ['咕噜噜……这里有闪亮的东西吗？', '伊格尼斯把尾巴努力藏在门外。'],
    bond1: ['你上次的东西不错，可以进我的小宝库。', '我没有想你，只是顺路来检查收藏来源。'],
    bond2: ['今天带了宝石，不许说太贵重。', '你的店闻起来像安全的巢穴。'],
    bond3: ['龙会守着最珍贵的东西，所以我来了。', '伊格尼斯骄傲地把柜台圈进守护范围。'],
  },
  necromancer: {
    bond0: ['生与死之间，需要一点指引。', '莫里斯从阴影里递出订单。'],
    bond1: ['你的灯没有驱赶我，这很少见。', '小骷髅坚持说今天应该来问候你。'],
    bond2: ['亡者低语嘈杂，与你说话却很安静。', '我带来一朵不会枯萎的黑玫瑰。'],
    bond3: ['若死亡之外仍有归处，也许就是这里。', '莫里斯摘下兜帽，声音比从前温柔。'],
  },
  fairy: {
    bond0: ['花园说这里有亮晶晶的魔法！', '蒂娜绕着灯飞了一圈。'],
    bond1: ['我又来啦！这次没有撞到窗户！', '上次的礼物花朵们都很喜欢。'],
    bond2: ['我给你带了晨露，只有最好的朋友才有。', '这里闻起来像会开花的梦。'],
    bond3: ['仙子的誓言很小，但每天都会发芽。', '蒂娜认真把一粒花籽放在柜台上。'],
  },
  demon: {
    bond0: ['嘿嘿……这里的灵魂气味很有趣。', '阿扎泽尔展开一张看似无害的契约。'],
    bond1: ['放心，今天的条款少了三个陷阱。', '你识破骗局的样子，确实让人想再来。'],
    bond2: ['我带来一笔赔本交易，只收你一句问候。', '地狱很吵，你这里更适合谈心。'],
    bond3: ['别误会，恶魔也会认真选择归处。', '阿扎泽尔收起契约，只把真名的一角留给你。'],
  },
};

const ROLE_GIFT_PREFERENCES = {
  traveler:     { star_letter: 1.4, memory_charm: 1.2, moon_cookie: 1.0, fate_crystal: 0.9 },
  knight:       { memory_charm: 1.4, moon_cookie: 1.2, star_letter: 1.0, fate_crystal: 0.9 },
  merchant:     { fate_crystal: 1.4, star_letter: 1.2, memory_charm: 1.0, moon_cookie: 0.9 },
  student:      { star_letter: 1.4, moon_cookie: 1.2, memory_charm: 1.0, fate_crystal: 0.8 },
  noble:        { fate_crystal: 1.4, memory_charm: 1.2, star_letter: 1.0, moon_cookie: 0.8 },
  farmer:       { moon_cookie: 1.4, memory_charm: 1.2, star_letter: 1.0, fate_crystal: 0.8 },
  lover:        { star_letter: 1.5, memory_charm: 1.2, moon_cookie: 1.0, fate_crystal: 0.9 },
  scholar:      { memory_charm: 1.4, star_letter: 1.2, fate_crystal: 1.0, moon_cookie: 0.9 },
  ghost:        { memory_charm: 1.5, star_letter: 1.1, moon_cookie: 0.9, fate_crystal: 0.9 },
  elf:          { moon_cookie: 1.3, memory_charm: 1.3, star_letter: 1.1, fate_crystal: 0.9 },
  dwarf:        { memory_charm: 1.4, fate_crystal: 1.2, moon_cookie: 1.0, star_letter: 0.9 },
  vampire:      { fate_crystal: 1.4, memory_charm: 1.3, star_letter: 1.0, moon_cookie: 0.8 },
  priest:       { moon_cookie: 1.3, star_letter: 1.3, memory_charm: 1.0, fate_crystal: 0.8 },
  witch_hunter: { memory_charm: 1.4, moon_cookie: 1.1, star_letter: 1.0, fate_crystal: 0.9 },
  bard:         { star_letter: 1.5, moon_cookie: 1.1, memory_charm: 1.0, fate_crystal: 0.9 },
  alchemist:    { fate_crystal: 1.4, memory_charm: 1.2, star_letter: 1.0, moon_cookie: 0.8 },
  dragon:       { fate_crystal: 1.6, memory_charm: 1.1, moon_cookie: 1.0, star_letter: 0.8 },
  necromancer:  { memory_charm: 1.4, fate_crystal: 1.3, star_letter: 1.0, moon_cookie: 0.8 },
  fairy:        { moon_cookie: 1.6, star_letter: 1.1, memory_charm: 1.0, fate_crystal: 0.8 },
  demon:        { fate_crystal: 1.4, star_letter: 1.3, memory_charm: 1.0, moon_cookie: 0.8 },
};

const ROLE_PRODUCT_GIFT_PREFERENCES = {
  traveler:     { travel: 1.5, luck: 1.2, comfort: 1.1 },
  knight:       { protection: 1.5, safety: 1.3, healing: 1.1 },
  merchant:     { trade: 1.5, luck: 1.3, metal: 1.1 },
  student:      { story: 1.4, mystery: 1.2, comfort: 1.1 },
  noble:        { fate: 1.4, mystery: 1.2, trade: 1.1 },
  farmer:       { healing: 1.4, daily: 1.2, comfort: 1.1 },
  lover:        { gentle: 1.4, dream: 1.3, story: 1.1 },
  scholar:      { mystery: 1.4, story: 1.3, fate: 1.1 },
  ghost:        { dream: 1.5, fate: 1.2, gentle: 1.1 },
  elf:          { healing: 1.3, gentle: 1.3, dream: 1.1 },
  dwarf:        { craft: 1.5, metal: 1.3, trade: 1.1 },
  vampire:      { mystery: 1.4, fate: 1.2, dream: 1.1 },
  priest:       { holy: 1.5, protection: 1.2, healing: 1.1 },
  witch_hunter: { protection: 1.5, safety: 1.3, mystery: 0.9 },
  bard:         { story: 1.5, luck: 1.2, travel: 1.1 },
  alchemist:    { craft: 1.5, metal: 1.3, trade: 1.1 },
  dragon:       { metal: 1.5, craft: 1.2, fate: 1.1 },
  necromancer:  { mystery: 1.5, fate: 1.3, dream: 1.1 },
  fairy:        { gentle: 1.5, healing: 1.3, luck: 1.1 },
  demon:        { fate: 1.5, trade: 1.3, holy: 0.8 },
};

CUSTOMER_TYPES.forEach(role => {
  role.giftPreferences = ROLE_GIFT_PREFERENCES[role.id] || {};
  role.productGiftPreferences = ROLE_PRODUCT_GIFT_PREFERENCES[role.id] || {};
  role.special = true;
  role.npcType = 'special';
  role.title = role.name;
  role.visitLines = SPECIAL_NPC_VISIT_LINES[role.id] || null;
});

/* ─── STORY ENTRIES ─── */
const ROLE_STORY_THRESHOLDS = [1, 3, 5, 8, 12, 16, 21, 27];

const ROLE_SIGNATURE_GIFTS = {
  traveler: 'star_letter',
  knight: 'memory_charm',
  merchant: 'fate_crystal',
  student: 'star_letter',
  noble: 'fate_crystal',
  farmer: 'moon_cookie',
  lover: 'star_letter',
  scholar: 'memory_charm',
  ghost: 'memory_charm',
  elf: 'moon_cookie',
  dwarf: 'memory_charm',
  vampire: 'fate_crystal',
  priest: 'star_letter',
  witch_hunter: 'memory_charm',
  bard: 'star_letter',
  alchemist: 'fate_crystal',
  dragon: 'fate_crystal',
  necromancer: 'memory_charm',
  fairy: 'moon_cookie',
  demon: 'fate_crystal',
};

// 每个预设角色（身份 + 性格）各 8 段乙女向事件；按完成该角色订单次数逐步解锁。
const ROLE_STORY_LIBRARY = {
  // ◆ 塞勒斯 · 旅行者
  "traveler": [
    ["制图师的习惯", "他把一枚铜币放在柜台上旋转，说这是判断桌面是否水平的旅人窍门。铜币倒向你的方向时他没去接，只说：\"嗯，引力偏向了很好的方位。\"你瞥见他摊开的笔记本，最新一页画着你店门口那棵歪脖子橡树。"],
    ["第七次路过", "他承认这条路线根本不经过你的小镇，是特意绕了十六里山路。你问为什么，他从口袋掏出上次你随手给他的糖纸折的青蛙：\"它跳不远，所以我得替它回来。\""],
    ["四十三种泥土", "他脱下靴子给你看鞋底——左脚沾着红土沙漠的赭石，右脚是北方冻原的黑泥。\"还差最后一种。\"他光脚踩上你店门口的青苔地砖，\"这种绿色的，我想天天踩到。\""],
    ["画不完的肖像", "素描本被风吹开，里面有七张你的速写：搅药锅的背影、数金币的侧脸、打哈欠的模糊轮廓。他慌忙合上本子，解释说制图师需要练习人物画……但画了七遍还是抓不住你眼睛的颜色。"],
    ["北极光欠条", "他留下一张手写\"欠条\"：欠魔女一次北极光。底下小字写着兑现条件——你愿意和他同行三天。三天刚好够走到他发现的秘密山谷，那里冬天能看见绿色的天空。"],
    ["迷路的指南针", "他的铜耳饰指南针坏了，指针一直朝着你的店转。修好后它恢复正常，他却把坏掉的指针留了下来。\"有些错误比正确答案更诚实。\""],
    ["最后一块空白", "世界地图只剩最后一块空白，填完他就能交差回皇都。他犹豫了整整两周没有动笔。你问原因，他说：\"画完就没有借口再来了。\""],
    ["定居坐标", "他在你的店铺坐标旁写下\"终点\"两个字，用红墨水圈了三圈。然后把钢笔放在你掌心，问：\"接下来的地图，你愿意和我一起画吗？\""],
  ],
  // ◆ 艾德里安 · 骑士
  "knight": [
    ["盔甲的声音", "他每次推门都会响起金属碰撞声，于是开始在门外先卸掉护腕和腿甲。你问他为什么，他认真说：\"怕吵到你调药。\"柜台下已经堆了三副护具。"],
    ["骑士的笨拙", "他想帮你搬药材木箱，戴着铁手套却拿不稳玻璃瓶。脱下手套后你看见他掌心全是老茧和剑痕，他握瓶子的手在轻微发抖。\"第一次怕摔坏东西。\"他低声说。"],
    ["巡逻改道", "你偶然得知他的巡逻路线本该在东城区，却每天绕三里路经过你店门口。副官抱怨说队长最近总\"确认森林边界安全\"，一天要确认五次。"],
    ["战袍内衬", "他的白色战袍内衬绣着精致的紫罗兰——那是你店门口最常见的野花。你指出来时，这位沉默寡言的骑士罕见地结巴：\"……骑士也、也可以有喜欢的花。\""],
    ["誓言之重", "骑士团授勋仪式上他拒绝晋升团长，理由是\"有更重要的承诺要守\"。第二天他把副团长勋章挂在你店里，说比起王城，他更想守着这扇门。"],
    ["无声守夜", "暴风雨夜你失眠到天明，推开门发现他在屋檐下站了一夜——全身湿透，剑没出鞘。他只说昨天占卜显示有危险，他不放心。盔甲上的雨水还在滴。"],
    ["剑刃钝了", "你注意到他的配剑刃口有缺损。他承认最近没去磨，因为休息时间都用来学怎么分辨草药、怎么不发出声音走路、怎么让你不那么辛苦。"],
    ["最后的荣耀", "骑士把家族传承的纹章剑插在你店门外的土地里，依古老骑士律法，这代表\"此生守护之地\"。剑柄上绑着他亲手编的铃兰花环，铃声很轻，像誓言。"],
  ],
  // ◆ 马库斯 · 商人
  "merchant": [
    ["零头的意义", "他结账时找你七枚铜币零头，你说不用了，他却坚持数到你掌心。\"商人的信誉就是准确。\"第二天他送来价值十金币的稀有香料，说是\"昨天算错的利息\"。"],
    ["成本核算", "他掏出小账本认真计算：\"你的笑容让我今天多跑了三家店询价，耽误两笔生意，路费八银币……\"你问总计多少，他合上本子：\"无价，但我愿意一直亏下去。\""],
    ["批发陷阱", "你要订购大批药材，他列出三家供应商报价，最后圈出最贵那家。\"他们会把你当长期客户，我已经谈好了——以后你的订单我来议价，作为……朋友的特权。\""],
    ["商队改道", "商队要去北方银矿，利润惊人，但他突然改道来你的小镇。合伙人质疑，他摊开账本，最后一页空着，只写了：\"有些东西不在账目里，却是最大的收益。\""],
    ["亏本的诚实", "你问他某批货物成本，商人本能犹豫三秒后，老实告诉你进价。这违反了商业原则，但他说：\"对你说谎的代价，比亏掉整个商队都大。\""],
    ["仓库钥匙", "他把私人仓库钥匙交给你，里面是十年积累的珍品。你说这太贵重，他认真说：\"我算过了，这些东西的价值加起来，也不如你说一句'谢谢'。\""],
    ["破产的觉悟", "为了救你店铺周转，他抵押了三条商路。你惊慌问他怎么办，他却轻松耸肩：\"我从贫民窟起家过一次，为你再来一次也不算亏。反正最珍贵的资产不能抵押。\""],
    ["最后的交易", "他拿出一份契约，甲方是他全部财产，乙方空白。\"这是我准备的聘礼清单，但我想先问你——愿意用一生的时间，换一个只会算计如何让你开心的商人吗?\""],
  ],
  // ◆ 林恩 · 学生
  "student": [
    ["掉落的笔记", "他进门时书包带子断了，笔记本散落一地。你帮他捡起时发现边角写满\"不要紧张\"的自我暗示，他脸红到耳根，结结巴巴说这、这是复习要点。"],
    ["安静角落", "学院图书馆最角落的位置永远是他的，直到你也开始在那里查资料。他紧张到翻书声音都小了三倍，却每次都把参考文献悄悄推到你面前。"],
    ["口吃的告白", "他练习了一个月终于鼓起勇气，却在说出\"我喜\"时卡住。你耐心等他说完，他急得眼眶泛红，最后从口袋掏出早就写好的纸条递给你。"],
    ["第一次并肩", "实验课分组，他被分到你这组。配药时他手一直在抖，你握住他的手说\"慢慢来\"，他深吸一口气，那次实验得了全班最高分。"],
    ["雨中护书", "暴雨突袭，他把唯一的外套罩在你借给他的珍贵药典上，自己淋得透湿。你责备他，他却笑着说：\"书是你的，比我重要。\""],
    ["期末守夜", "期末考前他通宵复习在图书馆睡着，你给他披上披肩。他醒来发现旁边多了热可可和便签：\"林恩会考得很好的。\"他把便签夹进了毕业相册第一页。"],
    ["答辩勇气", "毕业答辩上，评委质疑他的研究，他第一次没有低头。\"这个方法是森林魔女教我的，她比任何人都懂药草。\"为了你，他学会了反驳。"],
    ["不再口吃", "毕业后他回到小店，这次没有结巴，清晰地说出完整的句子：\"我用了三年学会流利说话，就为了告诉你——我想用余生陪伴你。\""],
  ],
  // ◆ 艾里克 · 贵族
  "noble": [
    ["高傲的挑剔", "他进门第一句话是嫌弃椅子灰尘，第二句是质疑你的资质。喝下药水后他沉默了整整三十秒，最后丢下一袋金币，冷冷说：\"下次我会提前预约。\""],
    ["贵族的道歉", "管家送来绣着家徽的道歉信和一箱珍稀香料。信尾罕见手写了一行小字：\"若冒犯了真正有本事的人，是我失礼。——艾里克。\"第一次，他没署公爵头衔。"],
    ["宴会舞伴", "他亲自登门递来舞会请柬，说贵族间规矩要找门当户对的舞伴。你正要拒绝，他却移开视线：\"但若你愿意，我可以当一晚上不是公爵。\""],
    ["银器与围裙", "他来店里时你正忙得一团糟，他居然挽起袖子帮你分拣药材。你震惊地看着他用戴满宝石的手指小心翼翼捏起草叶，他认真说：\"总得学点有用的技能。\""],
    ["谣言的代价", "王城有贵族编排你的谣言，次日那家族的商业执照全被吊销。他来店里时眼神疲惫：\"我不喜欢用权力压人，但伤害你是我唯一的底线。\""],
    ["温室秘密", "他私人温室里有一个禁止他人进入的角落，全是你店门口常见的野花。园丁偷偷告诉你：\"公爵每天早晨第一件事就是来这里待半小时。\""],
    ["摘下徽章", "贵族议会要求他在你和爵位间二选一。他当着所有人的面摘下家族徽章放在桌上，平静说：\"若贵族的定义不包括守护珍视之人，这身份我不要也罢。\""],
    ["平民的求婚", "月夜花园里，他没有准备任何贵族仪式，只是单膝跪地，认真问：\"我可以用余生学习成为配得上你的普通人吗？\"手里的戒指是他亲手打磨的。"],
  ],
  // ◆ 托马斯 · 农夫
  "farmer": [
    ["泥手的笨拙", "他来买药时手在衣服上蹭了三次才敢接瓶子，怕弄脏。你说不介意，他却红着脸说：好东西都该被干净的手捧着，包括你递过来的药。"],
    ["麦田邀请", "他笨拙地邀请你去看麦田，理由是\"魔女应该知道草药长在哪\"。走到田埂时他把草帽扣你头上，小声说怕你晒黑，又怕你嫌他土气。"],
    ["过期的种子", "他送来一包种子说是谢礼，你发现是珍贵的药草种。他挠头说本想自己种，但怕种不好，还是交给懂的人——就像他的心。"],
    ["雨中抢收", "暴雨前他急着抢收药草，你去帮忙。他坚持让你站在防雨布下，自己淋得透湿。你生气时，他憨笑：\"庄稼人不怕淋，你不一样。\""],
    ["谷仓避雨", "你们被困在谷仓过夜，他把唯一的毯子给你，自己靠着草垛。你问他冷不冷，他摇头说，看着你暖和他就不冷了。"],
    ["丰收的真相", "今年大丰收，他却说多亏了你的药。村长揭穿他每天天不亮就去你店门口除草、修台阶、补窗缝：\"你那药哪有让他勤快的功效。\""],
    ["泥土戒指", "他用麦秆编了个戒指，不好意思地说等攒够钱换真的。你戴上后他眼眶泛红：\"我这辈子最好的收成，就是你愿意戴它。\""],
    ["四季誓言", "他在田埂跪下，手心摊开一把泥土：\"我没读过书，只会种地。但我想用春天耕耘、夏天守护、秋天收获、冬天陪伴，把每一季都过成你的。\""],
  ],
  // ◆ 朱利安 · 恋人
  "lover": [
    ["代笔的生意", "他来请你帮忙鉴定爱情符咒效果，因为委托人说表白总失败。你看完他代笔的情书，指出问题：\"你把心动都写给了错的人。\"他愣住了。"],
    ["粉色的意外", "他整理文件时掉出一张粉色信纸，抬头写着你的名字。他慌忙解释这是练习措辞——但十七页草稿都是同一个收信人，连措辞都没改。"],
    ["书记员的私藏", "镇公所有人说书记员有个上锁的抽屉，你偶然看见里面全是写着你名字的情书草稿。从春天的\"尊敬的魔女\"写到冬天的\"我喜欢你\"。"],
    ["雨中情书", "他淋着雨把一封信塞到你手里就跑，信纸湿透但字迹工整。写了整整三页，最后一句是：\"我终于鼓起勇气，不替别人写，而是为自己写。\""],
    ["退稿的勇气", "有贵族请他代笔追求你，他破天荒拒绝了。你问他原因，他深吸一口气：\"因为关于你的句子，我一个字都不想分给别人。\""],
    ["爱情理论", "他带来一本写满理论的笔记，认真分析告白成功率。翻到最后一页，只有一句潦草的话：\"遇见你，所有理论都失效了。\""],
    ["书记员失职", "镇长抱怨他最近工作总出错，因为老走神。你去找他时，他正在公文背面画你的侧脸素描，纸堆里藏着至少二十张。"],
    ["墨水的告白", "他把一瓶特调墨水交给你，说是新配方。你用它写字时，纸上浮现出他的笔迹：\"我爱你\"三个字，用了他练习一千遍的最美字体。"],
  ],
  // ◆ 维克多 · 学者
  "scholar": [
    ["第十三个问题", "他每次来都要问十二个学术问题，你已经习惯。第十三次见面时，他破天荒问了私人问题：\"你会喜欢一个只会提问的学者吗？\""],
    ["笔记本入侵", "他请你帮忙查资料，你翻开他笔记本，发现学术公式之间夹着：\"今天魔女笑了三次\"\"她调药的手很好看\"\"如何用科学解释心动\"。"],
    ["实验失控", "他的药剂实验失败喷了你一身，他手忙脚乱地帮你擦拭，紧张到语无伦次。最后他脱下外袍披在你身上，红着脸说：对不起，这是我最失败的实验。"],
    ["论文署名", "他发表的重要论文里致谢部分用了整整半页写你，学术界震惊。导师质疑时，他认真说：\"她的存在让我理解了研究的意义，这比任何公式都重要。\""],
    ["通宵陪伴", "你通宵赶制药剂，他默默坐在角落看书陪你。天亮时你发现他的书从未翻页，他承认：\"观察你比任何研究都让我专注。\""],
    ["学术争论", "你们为药理和魔法理论大吵一架，谁也不服。最后他忽然笑了：\"能让我愿意争论一整夜的人，大概已经住进了我的所有假设里。\""],
    ["失眠处方", "他说失眠三年，所有方法都试过。你给他调药时他却睡着了，醒来后他看着你，轻声说：\"原来处方不是药，是你在身边。\""],
    ["终身课题", "他把一枚刻满公式的戒指递给你，说这是计算过的最优解。公式的结论只有一个：在所有可能的未来里，有你的那个概率最高，幸福指数也最大。"],
  ],
  // ◆ 埃利亚斯 · 幽灵
  "ghost": [
    ["午夜访客", "他第一次出现时把你吓了一跳，却比你更慌张。飘在半空结结巴巴道歉，说他只是被灯光吸引，已经很久没见过有人点灯到这么晚了。"],
    ["透明的帮忙", "你熬夜配药，他飘在旁边想帮忙却什么都拿不起。最后他开始轻声哼曲子给你解闷，曲调忧伤又温柔，你抬头时他正认真看着你。"],
    ["旧琴的秘密", "他总盯着店角落蒙尘的旧钢琴。你擦干净后他激动到实体化了一秒，指尖在琴键上留下一个音。那是他生前最后想弹却没弹完的曲子。"],
    ["冰冷的玫瑰", "清晨你发现柜台上有一朵结满霜的玫瑰，他飘在窗边不敢靠近。\"幽灵碰过的东西都会变冷，但我……还是想送你花。\"他声音小得像叹息。"],
    ["被看见的孤独", "你问他为什么不去转生，他沉默很久说不记得了。你陪他翻生前的旧物，看到演出海报上年轻的他，他哭了，眼泪落下时像月光碎片。"],
    ["温度的意义", "他说最羡慕你能感受温暖。你把手放在他穿过的空气里，认真说：\"你的陪伴也是温暖。\"那天晚上，他的轮廓比以往都清晰。"],
    ["转生之门", "亡灵节那晚，转生之门为他打开。他看着门后的光，又回头看你，最后握紧透明的拳头：\"对不起，我还不想忘记你。\"门在他面前关闭了。"],
    ["永恒的守夜", "他说选择留下后，记忆开始回来了——他是在等一个约定。\"原来我一直在等的人，\"他靠近你，虚幻的手停在你脸颊旁，\"就是你。\""],
  ],
  // ◆ 希尔凡 · 精灵
  "elf": [
    ["林间初遇", "他从树冠飘然落下，赤足无声。你以为会责备你采摘药草，他却蹲下检查你留下的切口，认真说：\"懂得尊重的人类，森林一百年没见过了。\""],
    ["古树下的茶", "他用露水泡茶，说这是三百岁橡树的晨露。你尝到青草和阳光的味道，他看你的眼神温柔得像春天：\"能分享它的，只有特别的人。\""],
    ["风语翻译", "他教你听风的语言，你什么都听不懂。他轻笑着靠近，替你拂开被风吹乱的碎发：\"风说，它喜欢看见我笑，而我只在你面前笑。\""],
    ["守夜的银弓", "森林边界有魔物徘徊，他整夜站在你店铺屋顶。黎明时你发现他长发上结满露珠，他只是摇头：\"守护重要的东西，是精灵的本能。\""],
    ["月桂冠的秘密", "他编了一顶月桂花冠要你戴上，说是森林的祝福。族中长老告诉你，精灵只会给生命伴侣编月桂冠，他转了三百年都没编过。"],
    ["季节之瞳", "你第一次注意到他眼睛会变色。他解释说精灵之瞳映照四季，但看着你时，瞳色定格在春天的嫩绿：\"因为你让我想永远停在万物初生的时刻。\""],
    ["不老的诺言", "他说精灵的寿命是诅咒，看着珍视的人老去是最深的痛。你握住他的手问会不会后悔，他摇头：\"即使只有你的一生，也比我的永恒更珍贵。\""],
    ["根系相连", "森林最古老的树为你们开出一条通道，树根交织成拱门。他牵起你的手穿过：\"精灵的婚礼不需要誓言，因为森林已经把我们的根连在了一起。\""],
  ],
  // ◆ 格罗因 · 矮人
  "dwarf": [
    ["门槛修补匠", "粗鲁的矮人把金币摔得震天响，嘴里嘟囔着要最烈的药水。临走时却停下，掏出小锤把你磨损的门槛修平，说：\"免得你这小魔女摔倒。\""],
    ["石研钵礼物", "他送来一只沉甸甸的花岗岩研钵，说是矿洞深处的好石头。你惊讶它的重量，他别过脸小声说：\"好东西就该结实，像我对你的……算了。\""],
    ["矿洞遇险", "你陪他去矿洞采集发光苔藓，他嘴上嫌你走得慢，粗糙的手却一直护在旁边。地面突然塌陷时，他毫不犹豫把你抱进怀里，用后背撞上岩壁。"],
    ["胡须的秘密", "矮人族最重视胡须，他的三股辫里藏着祖传的铭文铃铛。你帮他整理时他紧张得僵住，族中长老说只有妻子才能碰矮人的胡辫。"],
    ["铁匠的笨拙", "他锻造了一枚秘银发簪，手法精湛，包装却像是用矿石袋随便裹的。你戴上时他盯了很久，结结巴巴：\"还……还行，配得上你。\""],
    ["熔炉誓言", "矮人族的求爱仪式是共同锻造一件作品。他邀请你来锻炉边，你们的铁锤声交织在一起，他低声说：\"这是我们共同的节奏，会响一辈子。\""],
    ["酒馆醉话", "庆功宴上他喝多了，搂着你的肩膀对全酒馆宣布：\"这是我的魔女！谁敢欺负她，我就把他埋进矿洞最深处！\"第二天醒来他死不承认。"],
    ["石戒之约", "他打造了一枚能挡龙息的秘银戒指，戒面镶着你们初遇那天矿洞的水晶。他单膝跪地，用矮人古语郑重说：\"我的熔炉永远为你燃烧。\""],
  ],
  // ◆ 达里安 · 吸血鬼
  "vampire": [
    ["午夜来客", "优雅的吸血鬼只在午夜准时到访，手杖敲击地板的声音像古老的华尔兹节拍。他夸赞药水的香气迷人，停顿后补充：\"当然，不及你。\""],
    ["温热的红茶", "你为他准备了加热的红茶而非鲜血。他愣了三秒，然后认真品尝。月光下他轻声说：\"三百年来，第一次有人把我当客人，不是怪物。\""],
    ["古堡邀约", "黑鸦叼来烫金请柬，邀请你参加古堡晚宴。他在门口等了整整一小时，只为亲手为你披上天鹅绒披肩：\"今夜烛光只为你点燃。\""],
    ["血族的克制", "你不小心割伤手指，他瞳孔瞬间泛红，却立刻后退三步。他双手死死攥着手杖，低声道歉：\"越在乎的人，越不敢让本能靠近。\""],
    ["收藏室秘密", "他带你参观珍藏数世纪的宝物，却在一朵干枯玫瑰前停留最久。那是你上次随手插在药瓶上的花，被他用魔法永久保存。"],
    ["黎明的温度", "你调制出能让吸血鬼短暂承受阳光的药剂。清晨他站在窗边，看着第一缕晨光照在你脸上：\"原来你每天醒来，都被这样温柔的光包围。\""],
    ["永恒的诅咒", "他说不朽是最残酷的惩罚，因为会目送所有珍视之人离开。你握住他冰冷的手，他哑声说：\"但如果不遇见你，这永恒更加空洞。\""],
    ["血月誓约", "血月之夜，他用家族传承的仪式献上自己的真名与血契。\"我的永恒属于你，哪怕只换来你的一生，我也甘愿。\"他吻上你的指尖。"],
  ],
  // ◆ 塞巴斯 · 牧师
  "priest": [
    ["圣光疑问", "虔诚的牧师谨慎询问你的魔法是否会冒犯神明。你展示治愈药水后，他合掌微笑，说善意本身就是最纯净的祈祷。"],
    ["钟声早餐", "清晨钟声后，他送来神殿烤面包，理由是你常忙到忘记吃饭。祝福词念到一半，他忽然卡壳，因为你笑得太近。"],
    ["忏悔室秘密", "他在忏悔室里低声承认最近祈祷总会想到你。隔着木窗，他看不见你的表情，却听见自己心跳比钟声更响。"],
    ["祝福手绳", "他编了一条白色手绳，说能驱散恶意。系上时他的指尖微颤，像在完成一场比仪式更私人的承诺。"],
    ["雨夜收留", "暴雨冲垮小桥，他留在小店帮忙照看病人。夜深时他为你披上毯子，轻声说神会原谅他把目光多停留一会儿。"],
    ["教义与心意", "长老质疑他频繁来往魔女小店，他平静回应：若信仰要求远离善良，那他愿重新理解信仰。你的名字让他变得勇敢。"],
    ["圣坛花束", "节庆礼拜后，圣坛上多了一束紫色小花。他说献给神明，也献给让他理解爱与慈悲并不矛盾的人。"],
    ["以光为誓", "牧师在晨光中握住你的手，郑重得像宣读圣典。“我愿以余生证明，靠近你不是堕落，而是我被光引领的方向。”"],
  ],
  // ◆ 加雷特 · 猎魔人
  "witch_hunter": [
    ["刀锋审视", "谨慎的猎魔人第一次进店时手不离刀，眼神冷得像银刃。可你救下他追踪时受伤的手臂后，他沉默许久，只说欠你一次。"],
    ["安全距离", "他总站在门边，方便随时撤退。第三次来时却主动坐到柜台前，把武器放远一点：“今天我想试着相信你。”"],
    ["共猎黄昏", "你提供追踪药粉协助他狩猎魔物，他负责挡住危险。黄昏归来时，他把战利品交给你，说没有你的魔法，他赢不了。"],
    ["误会通缉", "城里有人诬告你使用黑魔法，他连夜调查证据。面对审判官，他第一次为魔女拔刀，声音冷静得不容置疑。"],
    ["伤痕地图", "他让你查看身上旧伤，每一道都来自曾经的不信任。你轻轻涂药时，他低声说，也许他最该猎杀的是自己的偏见。"],
    ["银刃护符", "他把一小片银刃磨成护符送你，能警示恶意。你问他不怕削弱武器吗，他回答真正的武器已经学会保护你。"],
    ["篝火坦白", "追猎途中你们共守一堆篝火，他讲起失去同伴的过去。火光映在他眼里，他说不想再把重要的人留在危险之外。"],
    ["放下猎名", "他递交辞呈，不再以猎魔人为唯一身份。走进小店时，他空着双手，认真地问：我能不能作为一个爱慕你的人留下？"],
  ],
  // ◆ 菲恩 · 吟游诗人
  "bard": [
    ["跑调情歌", "欢快的吟游诗人一进门就弹错三个和弦，却坚持说这是即兴。你笑出声后，他立刻宣布这将成为新曲《魔女的笑声》。"],
    ["押韵订单", "他每次点单都要押韵，害你差点把药材放错。赔礼时他送你一段短诗，最后一句藏着你的名字，念起来像亲吻。"],
    ["广场传唱", "小镇广场开始流行一首歌，唱森林魔女如何点亮夜晚。你找他算账，他眨眼说艺术需要真实，而他的真实全与你有关。"],
    ["破弦夜曲", "演出前琴弦断裂，你用小魔法帮他修好。他在台上临时改曲，把谢幕时最深的鞠躬献给后台的你。"],
    ["旅行剧团", "剧团邀请他离开，他却犹豫不决。你说机会难得，他反问：“如果最想写的故事在这里，我为什么要去远方？”"],
    ["雨巷二重奏", "雨夜他在巷口为你撑伞，雨点敲成节拍。他哼着旋律让你填词，你随口一句，他竟郑重写进随身歌本。"],
    ["沉默的歌者", "他嗓子哑了，却仍用纸条逗你笑。最后一张纸条写着：原来不能唱歌时，我还是最想把心意告诉你。"],
    ["终曲献名", "庆典压轴曲名为你的名字。全场欢呼中，他跳下舞台牵起你的手：“我唱过很多传说，但只想和你写余生。”"],
  ],
  // ◆ 奥利弗 · 炼金术士
  "alchemist": [
    ["冒烟同行", "古怪的炼金术士抱着冒烟烧瓶冲进店里，兴奋地称你为同行。爆炸声后，他第一反应不是救实验，而是检查你有没有受伤。"],
    ["反重力午餐", "他的实验让午餐漂到天花板，你们只能站在椅子上抢面包。混乱中他笑得灿烂，说与你合作连失败都可爱。"],
    ["奇妙配方", "他提出把月露、糖霜和一点点心跳加入新药。你问心跳怎么量，他立刻贴近，认真表示自己可以提供样本。"],
    ["玻璃温室", "炼金温室里开满金属花，他说每朵都会记录访客声音。你靠近一朵，里面反复播放的是他练习邀请你约会的话。"],
    ["失忆药剂", "他误饮短效失忆药水，却仍本能地把你护在身后。恢复后他得意宣布：看来喜欢你已经写进灵魂反应式。"],
    ["同行竞争", "学院比赛中你们被分到对手组，他嘴上宣战，暗地却把最佳材料留给你。你质问他，他说胜负没有你开心重要。"],
    ["炼金心脏", "他展示一枚机械心脏，说能模拟情绪。机器一靠近你就剧烈跳动，他却摸着自己胸口承认：真品也是这样。"],
    ["贤者之吻", "传说贤者之石能实现愿望，他终于炼成一小块，却用来做你的戒面。他说永生和黄金都无聊，唯有与你相爱值得研究一生。"],
  ],
  // ◆ 伊格尼斯 · 幼龙
  "dragon": [
    ["龙尾捣乱", "顽皮的幼龙把尾巴伸进药材柜，弄得满地亮晶晶。他被你瞪了一眼后乖乖收好翅膀，却偷偷把最闪的宝石推给你。"],
    ["金币窝垫", "他邀请你参观自己的宝物窝，骄傲地说最软的位置留给贵客。你坐下后，他立刻补充：也是留给最喜欢的人类。"],
    ["喷嚏火花", "幼龙感冒喷出小火花，差点点燃窗帘。你喂他药水时，他委屈地把下巴搁在你手心，像一只超大号撒娇猫。"],
    ["飞行试乘", "他坚持带你低空飞行，绕着森林转了一圈又一圈。落地后他得意地问怕不怕，你说还好，他反而红了耳鳞。"],
    ["藏宝清单", "他开始把你的发带、便签和空药瓶列入藏宝清单。你抗议后，他认真解释龙只收藏最珍贵的东西。"],
    ["成年礼角", "幼龙成年礼需要装饰龙角，他把选择权交给你。你系上一条紫丝带，他在族人面前炫耀了整整三天。"],
    ["守护领地", "有盗贼靠近小店，他盘在屋顶发出低吼。事后他装作只是保护领地，可领地边界明显只圈住了你的窗户。"],
    ["龙族求偶", "他带来一山洞宝石，郑重询问够不够做求偶礼。你说太夸张，他立刻收起大半，只留下最像你眼睛颜色的一颗。"],
  ],
  // ◆ 莫里斯 · 死灵法师
  "necromancer": [
    ["黑袍低语", "神秘的死灵法师站在阴影里，声音像从古井传来。你递给他温热药剂时，他罕见停顿，说已经很久没人给他“温度”。"],
    ["骷髅信使", "一只小骷髅送来订单和一朵歪头雏菊。纸条上写着\"它坚持认为你会喜欢\"，字迹却暴露了真正挑花的人。"],
    ["亡者舞会", "他邀请你参加只在月食出现的舞会。骷髅乐手奏起旧曲，他隔着黑手套牵你旋转，礼貌得近乎虔诚。"],
    ["灵魂占卜", "你为他占卜灵魂回声，看见他少年时害怕孤独的影子。他合上水晶球，低声说如今影子旁边多了你。"],
    ["禁书书签", "他借你一本禁书，里面夹着黑玫瑰书签。每次翻页，书签都会浮现一句提醒：早点休息，别让某位死灵法师担心。"],
    ["白昼练习", "为了不吓到客人，他练习在白天微笑，结果更像诅咒。你笑到扶柜台，他无奈叹息，却把你的笑声称作最有效的复活术。"],
    ["生死边界", "亡灵失控时他让你先走，你却留下协助结界。尘埃落定后，他握住你的手，第一次显露真实恐惧：差点失去你，比死亡可怕。"],
    ["永眠之前", "他把灵魂契约烧毁，表示不再把自己锁在死亡里。“若你愿意，”黑袍下的眼神温柔，“我想学习怎样活着爱你。”"],
  ],
  // ◆ 蒂娜 · 花仙子
  "fairy": [
    ["花粉问候", "天真的花仙子洒下一串闪亮花粉，把你的头发变成临时花环。她慌忙道歉，你却笑了，于是她宣布这是今天最成功的魔法。"],
    ["露珠早餐", "她带来一枚露珠做的甜点，郑重得像献宝。你尝到清晨花香，她托腮看你，开心地拍翅膀拍到差点撞上灯。"],
    ["迷你约会", "她把茶杯改造成双人小船，邀请你在水盆里航行。虽然路线只有桌面一圈，她仍认真说这是仙子王国最高规格约会。"],
    ["花语误会", "她送你的花在花语里代表\"想每天见你\"，自己却完全不知道。你解释后，她整个人红成一颗覆盆子。"],
    ["翅膀雨衣", "下雨天她用叶片给自己做雨衣，又给你带来一把小到只能遮住手指的伞。你收下后，她幸福得在空中转圈。"],
    ["糖霜危机", "她偷吃糖霜陷进罐子里，被你救出来时满脸雪白。她严肃反省三秒，然后把第一口最甜的糖霜留给你。"],
    ["仙尘勇气", "为了保护花园，她第一次鼓起勇气面对乌鸦。你赶到时，她正颤抖着挡在花前，却还不忘喊你的名字给自己壮胆。"],
    ["小小誓言", "她把一枚花籽放进你掌心，说仙子的爱会开花。第二天窗台长出一株迷你玫瑰，每片花瓣都写着“喜欢你”。"],
  ],
  // ◆ 阿扎泽尔 · 恶魔
  "demon": [
    ["契约笑意", "狡猾的恶魔把契约卷轴铺满柜台，条款华丽又危险。你逐条划掉陷阱后，他反而笑得愉快，说聪明的魔女最让人着迷。"],
    ["赔本诱惑", "他提出用一个愿望换你的午后时间。你拒绝交易，他却照样留下高级材料，耸肩说偶尔赔本也能观察有趣反应。"],
    ["尾巴泄密", "恶魔嘴上说只是路过，尾巴却诚实地卷住柜台不肯走。你看向他，他立刻用翅膀遮脸，声称这是低等生理反应。"],
    ["地狱下午茶", "他邀请你品尝地狱甜点，外表恐怖却意外美味。看你喜欢，他得意宣布已买下那家店，只为以后随时哄你开心。"],
    ["灵魂不售", "有恶魔同族想买你的灵魂，他笑着挡在前面，语气仍轻佻却杀意森冷：“这位魔女的任何东西，都不在交易名单上。”"],
    ["真名筹码", "恶魔真名拥有束缚力量，他却把一半音节告诉你。你问为何信任，他避开视线：“因为你从不滥用别人交出的脆弱。”"],
    ["骗局反噬", "他设局想让你承认想他，结果被你反将一军。契约燃起粉色火焰，他盯着条款上\"心动者认输\"，罕见地沉默了。"],
    ["不公平交易", "他递来最后一份契约，条件只有一条：允许他长久陪在你身边。报酬栏写着他的真心，他说这是他做过最不狡猾的交易。"],
  ],
};

function _buildRoleStoryEntries() {
  return CUSTOMER_TYPES.flatMap(role => {
    const storyList = ROLE_STORY_LIBRARY[role.id] || [];
    return storyList.map((entry, index) => {
      const [title, body] = entry;
      
      return {
        id: `${role.id}_${role.personality}_story_${index + 1}`,
        roleId: role.id,
        charName: role.charName || role.name,
        roleName: role.name,
        emoji: role.emoji,
        scope: 'character',
        route: index < 4 ? 'public' : 'inner',
        characterIds: [role.id],
        title,
        text: body,
        unlockOrders: {
          identity: role.id,
          personality: role.personality,
          count: ROLE_STORY_THRESHOLDS[index],
        },
        unlockBond: {
          roleId: role.id,
          level: Math.max(0, Math.floor(index / 2)),
        },
        ...(index >= 4 ? {
          unlockGifts: {
            roleId: role.id,
            count: index - 2,
            ...(index >= 6 ? { giftId: ROLE_SIGNATURE_GIFTS[role.id] || 'memory_charm', giftCount: 1 } : {}),
          },
        } : {}),
        requirements: {
          orders: {
            identity: role.id,
            personality: role.personality,
            count: ROLE_STORY_THRESHOLDS[index],
          },
          bond: {
            roleId: role.id,
            level: Math.max(0, Math.floor(index / 2)),
          },
          ...(index >= 4 ? {
            gifts: {
              roleId: role.id,
              count: index - 2,
              ...(index >= 6 ? { giftId: ROLE_SIGNATURE_GIFTS[role.id] || 'memory_charm', giftCount: 1 } : {}),
            },
          } : {}),
        },
        preview: {
          hiddenTitle: index < 4 ? `${role.charName || role.name}的下一段故事` : `${role.charName || role.name}的深层心事`,
          hint: index < 4
            ? `${role.charName || role.name}似乎因为店里的往来，慢慢对你放下戒心。`
            : `${role.charName || role.name}还有一些不愿轻易说出口的事情。`,
          visibleHints: [
            `继续完成${role.charName || role.name}的委托`,
            '提升与 TA 的羁绊等级',
            ...(index >= 4 ? ['赠送适合 TA 的礼物'] : []),
          ],
          revealPolicy: 'partial',
        },
      };
    });
  });
}

const STORY_ENTRIES = [
  {
    id: 'intro',
    title: '第一章：小店开张',
    text: '在幽深的森林边缘，有一间小小的魔女小店。艾露娜——或者叫你起的名字——继承了祖母留下的魔法配方，决定开始她的经营之旅。\n\n「只要用心，每一杯魔药都能带去温暖。」',
    scope: 'prologue',
    route: 'archive',
    unlockPhase: 0,
    unlockCoins: 0,
    requirements: { phaseMin: 0, coinsEarnedMin: 0 },
  },
  ..._buildRoleStoryEntries(),
  {
    id: 'shop_missed_order_note',
    title: '柜台边的空纸袋',
    text: '打烊时，你在柜台边发现一个被遗忘的空纸袋。纸袋上用铅笔写着：「下次也许要早点来。」\n\n你把它夹进订单簿，没有责怪自己太久，只是在第二天开门前多点了一盏灯。小店第一次明白：没能完成的订单，也会留下需要被回应的心情。',
    scope: 'shop',
    route: 'if',
    unlockStats: { customersLostMin: 1 },
    requirements: { stats: { customersLostMin: 1 } },
    preview: {
      hiddenTitle: '被留下的纸袋',
      hint: '有位客人没能等到自己的订单完成。柜台边似乎留下了什么。',
      visibleHints: [
        '经历一次订单失手',
        '留意没能及时服务的客人',
      ],
      revealPolicy: 'partial',
    },
  },
  {
    id: 'shop_apology_list',
    title: '道歉名单',
    text: '第三个没能等到订单的客人离开后，你在账本背面写下一份短短的名单：有人需要安眠药水，有人想问远行的天气，还有人只是想带一块甜点回家。\n\n名字并不多，却足够让你重新整理货架和计时沙漏。祖母的旧笔记在边角处写着：「会补救的店，才有机会被再次信任。」',
    scope: 'shop',
    route: 'if',
    unlockStats: { customersLostMin: 3 },
    requirements: { stats: { customersLostMin: 3 } },
    preview: {
      hiddenTitle: '账本背面的名单',
      hint: '失手并不只是一串数字。也许该回头看看那些没能被完成的委托。',
      visibleHints: [
        '让店铺经历几次经营压力',
        '关注流失顾客留下的痕迹',
      ],
      revealPolicy: 'partial',
    },
  },
  {
    id: 'shop_reputation_crisis',
    title: '口碑危机',
    text: '傍晚时分，你在门口发现几张被风吹来的传单。上面写着：「森林边的小店最近总让客人空手而归。」\n\n这不是终点，却是一个提醒：每一次迟到、每一次失败，都会在小镇的耳语里留下痕迹。第二天清晨，有人敲响店门，没有责备，只问你是否需要帮忙重新整理订单簿。',
    scope: 'shop',
    route: 'if',
    unlockStats: { customersLostMin: 5 },
    requirements: { stats: { customersLostMin: 5 } },
    preview: {
      hiddenTitle: '小镇的耳语',
      hint: '最近似乎有些客人带着失望离开了。小镇上的传言开始变多。',
      visibleHints: [
        '让店铺经历一次经营压力',
        '关注没有被及时服务的客人',
      ],
      revealPolicy: 'partial',
    },
  },
  {
    id: 'shop_cozy_evening',
    title: '灯下的第一位客人',
    text: '新添置的软垫还带着阳光晒过的味道。傍晚，第一个主动留下来的客人没有急着离开，而是捧着茶杯问你：「这里以后也可以只是坐一会儿吗？」\n\n你忽然意识到，小店不只是售卖魔法的地方。它正在变成某些人愿意回来的坐标。',
    scope: 'shop',
    route: 'investment',
    unlockShopTraits: { comfortMin: 2 },
    requirements: { shopTraits: { comfortMin: 2 } },
    preview: {
      hiddenTitle: '更柔软的角落',
      hint: '如果店里有一个能坐下来慢慢说话的地方，也许客人会留下更多故事。',
      visibleHints: ['投资提升店铺舒适度'],
      revealPolicy: 'partial',
    },
  },
  {
    id: 'shop_midnight_ledger',
    title: '午夜账本',
    text: '夜深后，你整理账本，发现金币并没有消失：它们变成了书架、灯光、招牌，也变成了客人愿意多停留的几分钟。\n\n账页边缘浮现出祖母留下的一行小字：「会花钱的魔女，才知道怎样让一间店长出灵魂。」',
    scope: 'shop',
    route: 'investment',
    unlockStats: { coinsSpentTotalMin: 800 },
    unlockShopTraits: { wisdomMin: 2, fameMin: 2 },
    requirements: {
      stats: { coinsSpentTotalMin: 800 },
      shopTraits: { wisdomMin: 2, fameMin: 2 },
    },
    preview: {
      hiddenTitle: '被反复翻动的账页',
      hint: '当金币被持续投入店铺，旧账本也许会回应你。',
      visibleHints: ['累计投入金币', '提升知识与名声'],
      revealPolicy: 'partial',
    },
  },
  {
    id: 'grand_witch',
    title: '大魔女',
    text: '消息在小镇中传开了：「森林边那间小店的魔女，她的魔法是真的！」\n\n如今，来自四面八方的客人络绎不绝。你的祖母若是看到，一定会微笑的。\n\n「魔法，从未离我们而去。」',
    scope: 'shop',
    route: 'public',
    unlockOrders: { count: 30 },
    requirements: { orders: { count: 30 } },
    preview: {
      hiddenTitle: '更远处的传闻',
      hint: '当足够多的客人带着满意离开，森林边的小店会被更多人记住。',
      visibleHints: ['完成更多订单'],
      revealPolicy: 'partial',
    },
  },
];

/* ─── ROOM DECORATIONS (canvas drawing data) ─── */
const ROOM_DECORATIONS = [
  { emoji: '🕯️',  x: 0.08, y: 0.15 },
  { emoji: '🕯️',  x: 0.92, y: 0.15 },
  { emoji: '📚',  x: 0.15, y: 0.45 },
  { emoji: '🧺',  x: 0.82, y: 0.55 },
  { emoji: '🌿',  x: 0.05, y: 0.65 },
  { emoji: '🪄',  x: 0.88, y: 0.35 },
  { emoji: '⚗️',  x: 0.50, y: 0.20 },
  { emoji: '🦇',  x: 0.30, y: 0.08 },
  { emoji: '🦇',  x: 0.70, y: 0.12 },
];

/* ─── WITCH SPRITE STATES ─── */
const WITCH_EMOJI = {
  idle:    '🧙‍♀️',
  working: '🧙‍♀️',
  success: '🧙‍♀️',
};

/* ─── ALIASES (for backward compatibility / checker) ─── */
const SHOP_ITEMS = [...SHOP_UNLOCKS, ...SHOP_UPGRADES, ...SHOP_INVESTMENTS];
const PHASE_THRESHOLDS = PHASES.map(p => p.coinsNeeded);
const CUSTOMERS = CUSTOMER_TYPES;

/* MAX_PHASE */
// (defined in state.js as: const MAX_PHASE = PHASES.length - 1)
