const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const projectDir = path.join(root, 'witch-shop-game');
const archiveDir = path.join(projectDir, 'archives');

const requiredDocs = [
  'witch-shop-game/START_HERE.md',
  'witch-shop-game/AI_HANDOFF.md',
  'witch-shop-game/CHANGELOG.md',
  'witch-shop-game/docs/V3_ROADMAP.md',
  'witch-shop-game/docs/VERSION_ARCHIVE.md',
  'witch-shop-game/docs/DATA_CONTRACTS.md',
  'witch-shop-game/docs/QA_CHECKLIST.md',
  'witch-shop-game/STORY_SYSTEM_ROADMAP.md',
];

function exists(relPath) {
  return fs.existsSync(path.join(root, relPath));
}

function readText(relPath) {
  const fullPath = path.join(root, relPath);
  if (!fs.existsSync(fullPath)) return '';
  return fs.readFileSync(fullPath, 'utf8');
}

function getLatestArchives(limit = 5) {
  if (!fs.existsSync(archiveDir)) return [];
  return fs
    .readdirSync(archiveDir, {withFileTypes: true})
    .filter(entry => entry.isDirectory())
    .map(entry => entry.name)
    .sort()
    .slice(-limit)
    .reverse();
}

function getLatestChangelogEntry() {
  const changelog = readText('witch-shop-game/CHANGELOG.md');
  const matches = [...changelog.matchAll(/^##\s+(.+)$/gm)].map(match => match[1].trim());
  return matches.find(title => title !== 'Unreleased') || '未找到已发布迭代记录';
}

function getUnreleasedHighlights(limit = 5) {
  const changelog = readText('witch-shop-game/CHANGELOG.md');
  const start = changelog.indexOf('## Unreleased');
  if (start < 0) return [];
  const contentStart = changelog.indexOf('\n', start);
  if (contentStart < 0) return [];
  const nextSection = changelog.indexOf('\n## ', contentStart + 1);
  const section = changelog.slice(contentStart + 1, nextSection >= 0 ? nextSection : changelog.length);
  return section
    .split('\n')
    .filter(line => line.startsWith('- '))
    .map(line => line.slice(2).trim())
    .slice(0, limit);
}

function getCurrentPhase() {
  const handoff = readText('witch-shop-game/AI_HANDOFF.md');
  const match = handoff.match(/当前项目处于\s+\*\*(.+?)\*\*/);
  return match ? match[1] : '未能从 AI_HANDOFF.md 读取当前阶段';
}

function getRecommendedNextSteps(limit = 4) {
  const handoff = readText('witch-shop-game/AI_HANDOFF.md');
  const match = handoff.match(/优先解决：\s*\n([\s\S]*?)(?=\n##\s+|$)/);
  if (!match) return ['请查看 witch-shop-game/AI_HANDOFF.md 的“当前推荐下一步”'];
  const steps = match[1]
    .split('\n')
    .map(line => line.trim())
    .filter(line => /^\d+\./.test(line))
    .map(line => line.replace(/^\d+\.\s*/, ''))
    .slice(0, limit);
  return steps.length ? steps : ['请查看 witch-shop-game/AI_HANDOFF.md 的“当前推荐下一步”'];
}

function printSection(title) {
  console.log(`\n== ${title} ==`);
}

function printDocs() {
  printSection('Required handoff docs');
  requiredDocs.forEach(relPath => {
    console.log(`${exists(relPath) ? 'OK  ' : 'MISS'} ${relPath}`);
  });
}

function printArchives() {
  printSection('Latest archives');
  const archives = getLatestArchives();
  if (!archives.length) {
    console.log('MISS witch-shop-game/archives');
    return;
  }
  archives.forEach(name => console.log(`- witch-shop-game/archives/${name}/`));
}

function printStatus() {
  const startHere = 'D:\\mnemez\\project 02\\witch-shop-game\\START_HERE.md';

  console.log('Witch Shop Game handoff status');
  console.log('Generated by: node tools/handoff_status.js');

  printSection('Current summary');
  console.log('- Stable entry: witch-shop-game/START_HERE.md');
  console.log(`- Latest changelog entry: ${getLatestChangelogEntry()}`);
  console.log(`- Current phase: ${getCurrentPhase()}`);
  console.log('- Recommended next steps:');
  getRecommendedNextSteps().forEach(step => console.log(`  - ${step}`));

  const highlights = getUnreleasedHighlights();
  if (highlights.length) {
    console.log('- Unreleased highlights:');
    highlights.forEach(item => console.log(`  - ${item}`));
  }

  printDocs();
  printArchives();

  printSection('Shortest prompt for a new AI task');
  console.log(`请读取 ${startHere}，然后接手项目。`);

  printSection('Recommended commands');
  console.log('node tools/handoff_status.js');
  console.log('node tools/project_check.js');
}

printStatus();